/**
 ******************************************************************************
 * File Name          : f_lamp.c
 * Description        : This file is generated by 위대한 송 인재 on Sep 2, 2025
 ******************************************************************************
 *
 * COPYRIGHT(c) 2024 DSN Co. Ltd.
 *
 * Redistribution and use in source and binary forms, with or without modification,
 * are permitted provided that the following conditions are met:
 *   1. Redistributions of source code must retain the above copyright notice,
 *      this list of conditions and the following disclaimer.
 *   2. Redistributions in binary form must reproduce the above copyright notice,
 *      this list of conditions and the following disclaimer in the documentation
 *      and/or other materials provided with the distribution.
 *   3. Neither the name of STMicroelectronics nor the names of its contributors
 *      may be used to endorse or promote products derived from this software
 *      without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 ******************************************************************************
 */

#include "main.h"

/*******************************************************************************
 LAMP Object
 *******************************************************************************/
bool func_lamp_set(lamp_level_t lamp_level)
{
	assert (HAL_TIM_PWM_Stop(&htim4, TIM_CHANNEL_2) == HAL_OK);

	// 아래는 tim.c 에서 베껴옴..
	TIM_OC_InitTypeDef sConfigOC = {0};
	sConfigOC.OCMode = TIM_OCMODE_PWM1;
	sConfigOC.OCPolarity = TIM_OCPOLARITY_LOW;
	sConfigOC.OCFastMode = TIM_OCFAST_DISABLE;
	// Scopte 로 파형을 보니 PWM 신호가 low->high, high->low 로 갈 때 완전하게 가려면 50us 정도가 필요하다.
	// 그래서 Pulse 에 50 이하를 주는 것은 의미가 없으므로 1~9까지 9단계의 밝기를 만들 때 105 를 곱해서 최대 밝기가 945 가 되도록 한다.
	sConfigOC.Pulse = (uint32_t)(lamp_level * 105);
	assert (HAL_TIM_PWM_ConfigChannel(&htim4, &sConfigOC, TIM_CHANNEL_2) == HAL_OK);
	assert (HAL_TIM_PWM_Start(&htim4, TIM_CHANNEL_2) == HAL_OK);

	SMB_ControlObj.lampObj.lamp_level = lamp_level;
	return true;
}

lampObj_t *get_lamp_handle()
{
	return (&SMB_ControlObj.lampObj);
}

bool lampObj_init(lampObj_t *plampObj)
{
	plampObj->lamp_level = LAMP_LEVEL_0;
	plampObj->lamp_set = func_lamp_set;

	return true;
}
