/**
 ******************************************************************************
  * File Name          : func_ledbar.c
  * Description        : This file is generated by 위대한 송 인재 on Aug 27, 2025
 ******************************************************************************
 *
 * COPYRIGHT(c) 2024 DSN Co. Ltd.
 *
 * Redistribution and use in source and binary forms, with or without modification,
 * are permitted provided that the following conditions are met:
 *   1. Redistributions of source code must retain the above copyright notice,
 *      this list of conditions and the following disclaimer.
 *   2. Redistributions in binary form must reproduce the above copyright notice,
 *      this list of conditions and the following disclaimer in the documentation
 *      and/or other materials provided with the distribution.
 *   3. Neither the name of STMicroelectronics nor the names of its contributors
 *      may be used to endorse or promote products derived from this software
 *      without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 ******************************************************************************
 */

#include "main.h"

/*******************************************************************************
 LED BAR Object
 *******************************************************************************/
bool func_ledbar_color_set(ledbar_color_t ledbar_color)
{
	ledbar_color_t color = ledbar_color;

	switch (color) {
	case LEDBAR_OFF :		LED_R_Clear;	LED_G_Clear;	LED_B_Clear;	break;
	case LEDBAR_RED :		LED_R_Set;		LED_G_Clear;	LED_B_Clear;	break;
	case LEDBAR_GREEN :		LED_R_Clear;	LED_G_Set;		LED_B_Clear;	break;
	case LEDBAR_BLUE :		LED_R_Clear;	LED_G_Clear;	LED_B_Set;		break;
	case LEDBAR_YELLOW :	LED_R_Set;		LED_G_Set;		LED_B_Clear;	break;
	case LEDBAR_WHITE :		LED_R_Set;		LED_G_Set;		LED_B_Set;		break;
	default : assert (0 == 1); break;
	}

	SMB_ControlObj.ledbarObj.ledbar_color = ledbar_color;

	return true;
}

ledbarObj_t *get_ledbar_handle()
{
	return (&SMB_ControlObj.ledbarObj);
}

bool ledbarObj_init(ledbarObj_t *pledbarObj)
{
	pledbarObj->ledbar_color = LEDBAR_OFF;
	pledbarObj->ledbar_color_set = func_ledbar_color_set;

	return true;
}
