/**
 ******************************************************************************
 * File Name          : func_timer_list.c
 * Description        : This file is generated by 위대한 송 인재 on Aug 8, 2025
 ******************************************************************************
 *
 * COPYRIGHT(c) 2024 DSN Co. Ltd.
 *
 * Redistribution and use in source and binary forms, with or without modification,
 * are permitted provided that the following conditions are met:
 *   1. Redistributions of source code must retain the above copyright notice,
 *      this list of conditions and the following disclaimer.
 *   2. Redistributions in binary form must reproduce the above copyright notice,
 *      this list of conditions and the following disclaimer in the documentation
 *      and/or other materials provided with the distribution.
 *   3. Neither the name of STMicroelectronics nor the names of its contributors
 *      may be used to endorse or promote products derived from this software
 *      without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 ******************************************************************************
 */

#include "main.h"

extern osMessageQueueId_t		managerThreadQ;

static void led_act_toggle_timeout_cb (void *arg)
{
	led_act_toggle;
}

bool peri_oper_begin()
{
	assert (osTimerList[TMR_IDX_SMB_PERI_OPER].osTimerId != NULL);
	assert (osTimerStart(osTimerList[TMR_IDX_SMB_PERI_OPER].osTimerId, osTimerList[TMR_IDX_SMB_PERI_OPER].timeout_tick) == osOK);

	return true;
}

static void console_scan_timeout_cb (void *arg)
{
	osThreadFlagsSet(Thread_CLI_Handler, EF_CONSOLE_SCAN);
}

static void uptime_counter_timeout_cb (void *arg)
{
	SMB_StatusObj.uptime_counter++;
	assert (HAL_RTC_GetTime(&hrtc, &SMB_StatusObj.currentTime, RTC_FORMAT_BCD) == HAL_OK);
	assert (HAL_RTC_GetDate(&hrtc, &SMB_StatusObj.currentDate, RTC_FORMAT_BCD) == HAL_OK);
}

static void smb_adc_read_cb (void *arg)
{
	manager_msg_t manager_msg;

	memset (&manager_msg, 0, sizeof(manager_msg));
	manager_msg.head.type = MANAGER_MSG_ADC_READ;
	manager_msg.head.dst = WORKM_MANAGER;
	manager_msg.head.src = WORKM_TIMER;
	manager_msg.head.len = sizeof(manager_msg.head);

	osMessageQueuePut(managerThreadQ, &manager_msg, 0U, 0U);
}

static void smb_data_show_cb (void *arg)
{
	manager_msg_t manager_msg;

	memset (&manager_msg, 0, sizeof(manager_msg));
	manager_msg.head.type = MANAGER_MSG_DATA_SHOW;
	manager_msg.head.dst = WORKM_MANAGER;
	manager_msg.head.src = WORKM_TIMER;
	manager_msg.head.len = sizeof(manager_msg.head);

	osMessageQueuePut(managerThreadQ, &manager_msg, 0U, 0U);
}

static void smb_status_report_cb (void *arg)
{
	rb_msg_t rb_msg;

	memset (&rb_msg, 0, sizeof(rb_msg));

	rb_msg.head.type = RB_MSG_COMMAND;
	rb_msg.head.dst = WORKM_RB;
	rb_msg.head.src = WORKM_RB;
	rb_msg.head.len = RBERRY_MSG_LENGTH;

	rb_msg.rb_command.type = RB_REPORT_SENSOR_STATUS;
	rb_msg.rb_command.len = 0;
	rb_msg.rb_command.checksum = checksum((uint8_t *)&rb_msg.rb_command, 6);
	rb_msg.rb_command.end_marker = END_MARKER;

	osMessageQueuePut(rbThreadQ, &rb_msg, 0U, 0U);
}

static void SOH_req_timeout_cb (void *arg)
{
	iap_msg_t iap_msg;

	memset (&iap_msg, 0, sizeof(iap_msg));

	iap_msg.head.type = IAP_MSG_SOH_REQ_TIMEOUT;
	iap_msg.head.dst = WORKM_IAP;
	iap_msg.head.src = WORKM_UART4;
	iap_msg.head.len = 0;

	iap_msg.body.mpool = NULL;
	osMessageQueuePut(iapThreadQ, &iap_msg, 0U, 0U);
}

static void SMB_peri_oper_timeout_cb (void *arg)
{
	manager_msg_t manager_msg;

	memset (&manager_msg, 0, sizeof(manager_msg));
	manager_msg.head.type = MANAGER_MSG_PERI_OPER;
	manager_msg.head.dst = WORKM_MANAGER;
	manager_msg.head.src = WORKM_TIMER;
	manager_msg.head.len = sizeof(manager_msg.head);

	osMessageQueuePut(managerThreadQ, &manager_msg, 0U, 0U);
}

static void SMB_emer_btn_timeout_cb (void *arg)
{
	SMB_StatusObj.EMERGENCY.emer_by_button = false;
	if (IsThisEmergency() == false) assert (restore_peri_status() == true);		// 현재 진행 중인 비상 상황이 없을 때 peri 상태를 저장해 둔다.
}

static void SMB_motion_latency_timeout_cb (void *arg)
{
	SMB_StatusObj.smb_motion.motion = MOTION_NO;
}

static bool osTimerListConfigure(osTimerIndex_t index, osTimerType_t type, uint32_t timeout_tick, void (*cb)(void *))
{
	osTimerList[index].osTimerType = type;
	osTimerList[index].timeout_tick = timeout_tick;
	osTimerList[index].timeout_cb = cb;
	osTimerList[index].osTimerId = osTimerNew(osTimerList[index].timeout_cb, osTimerList[index].osTimerType, NULL, NULL);
	assert (osTimerList[index].osTimerId != NULL);

	return true;
}

bool osTimerList_init(osTimerEntry_t osTimerList[])
{
	for (uint32_t i = TMR_IDX_BEGIN ; i < TMR_IDX_END ; i++) {
		osTimerList[i].osTimerId_t = NULL;
		osTimerList[i].osTimerType = osTimerOnce;
		osTimerList[i].timeout_tick = 0;
		osTimerList[i].timeout_cb = NULL;
	}

	osTimerListConfigure (TMR_IDX_LED_ACT_TOGGLE, osTimerPeriodic, LED_ACT_TOGGLE_TIMEOUT, led_act_toggle_timeout_cb);
	osTimerListConfigure (TMR_IDX_CLI_CONSOLE_SCAN, osTimerPeriodic, CONSOLE_SCAN_TIMEOUT, console_scan_timeout_cb);
	osTimerListConfigure (TMR_IDX_UPTIME_COUNT, osTimerPeriodic, UPTIME_COUNT_TIMEOUT, uptime_counter_timeout_cb);
	osTimerListConfigure (TMR_IDX_ADC_READ, osTimerPeriodic, SMB_ADC_READ_TIMEOUT, smb_adc_read_cb);
	osTimerListConfigure (TMR_IDX_SMB_DATA_SHOW, osTimerPeriodic, SMB_DATA_SHOW_TIMEOUT, smb_data_show_cb);
	osTimerListConfigure (TMR_IDX_SMB_STATUS_REPORT, osTimerPeriodic, SMB_STATUS_REPORT_TIMEOUT, smb_status_report_cb);
	osTimerListConfigure (TMR_IDX_SMB_IAP_REQUEST, osTimerPeriodic, SOH_REQ_TIMEOUT, SOH_req_timeout_cb);
	osTimerListConfigure (TMR_IDX_SMB_PERI_OPER, osTimerPeriodic, SMB_PERI_OPER_TIMEOUT, SMB_peri_oper_timeout_cb);				//	Bench manager thread 는 주기적으로 peripheral control 을 한다.
	osTimerListConfigure (TMR_IDX_EMER_BTN, osTimerOnce, SMB_ConfigObj.siren_on_time*TIMEOUT_1_SEC, SMB_emer_btn_timeout_cb);	//	emergency button 을 누르면 시작하는 timer..
	osTimerListConfigure (TMR_IDX_MOTION_LATENCY, osTimerOnce, SMB_ConfigObj.motion_latency*TIMEOUT_1_SEC, SMB_motion_latency_timeout_cb);

	return true;
}
