/**
 ******************************************************************************
  * File Name          : func_timer_list.c
  * Description        : This file is generated by 위대한 송 인재 on Aug 8, 2025
 ******************************************************************************
 *
 * COPYRIGHT(c) 2024 DSN Co. Ltd.
 *
 * Redistribution and use in source and binary forms, with or without modification,
 * are permitted provided that the following conditions are met:
 *   1. Redistributions of source code must retain the above copyright notice,
 *      this list of conditions and the following disclaimer.
 *   2. Redistributions in binary form must reproduce the above copyright notice,
 *      this list of conditions and the following disclaimer in the documentation
 *      and/or other materials provided with the distribution.
 *   3. Neither the name of STMicroelectronics nor the names of its contributors
 *      may be used to endorse or promote products derived from this software
 *      without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 ******************************************************************************
 */

#include "main.h"

static void led_act_toggle_timeout_cb (void *arg)
{
	led_act_toggle;
}

static bool led_act_toggle_begin()
{
	assert (osTimerList[TMR_IDX_LED_ACT_TOGGLE].osTimerId != NULL);
	assert (osTimerStart(osTimerList[TMR_IDX_LED_ACT_TOGGLE].osTimerId, LED_ACT_TOGGLE_TIMEOUT) == osOK);

	return true;
}

static void console_scan_timeout_cb (void *arg)
{
	osThreadFlagsSet(Thread_CLI_Handler, EF_CONSOLE_SCAN);
}

static void uptime_counter_timeout_cb (void *arg)
{
	SMB_StatusObj.uptime_counter++;
	assert (HAL_RTC_GetTime(&hrtc, &SMB_StatusObj.currentTime, RTC_FORMAT_BCD) == HAL_OK);
	assert (HAL_RTC_GetDate(&hrtc, &SMB_StatusObj.currentDate, RTC_FORMAT_BCD) == HAL_OK);
}

static bool uptime_counter_begin()
{
	assert (osTimerList[TMR_IDX_UPTIME_COUNT].osTimerId != NULL);
	assert (osTimerStart(osTimerList[TMR_IDX_UPTIME_COUNT].osTimerId, UPTIME_COUNT_TIMEOUT) == osOK);

	return true;
}

bool osTimerList_init(osTimerEntry_t osTimerList[])
{
	for (uint32_t i = TMR_IDX_BEGIN ; i < TMR_IDX_END ; i++) {
		osTimerList[i].osTimerId_t = NULL;
		osTimerList[i].osTimerType = osTimerOnce;
		osTimerList[i].timeout_tick = 0;
		osTimerList[i].timeout_cb = NULL;
		strcpy (osTimerList[i].timer_description, "UNDEFINED TIMER");
	}

	osTimerList[TMR_IDX_LED_ACT_TOGGLE].osTimerType = osTimerPeriodic;
	osTimerList[TMR_IDX_LED_ACT_TOGGLE].timeout_tick = LED_ACT_TOGGLE_TIMEOUT;
	osTimerList[TMR_IDX_LED_ACT_TOGGLE].timeout_cb = led_act_toggle_timeout_cb;
	osTimerList[TMR_IDX_LED_ACT_TOGGLE].osTimerId = osTimerNew(osTimerList[TMR_IDX_LED_ACT_TOGGLE].timeout_cb, osTimerList[TMR_IDX_LED_ACT_TOGGLE].timeout_tick, NULL, NULL);
	assert (osTimerList[TMR_IDX_LED_ACT_TOGGLE].osTimerId != NULL);
	strcpy (osTimerList[TMR_IDX_LED_ACT_TOGGLE].timer_description, "OS_TIMER_INDEX_LED_ACT_TOGGLE");

	osTimerList[TMR_IDX_CLI_CONSOLE_SCAN].osTimerType = osTimerPeriodic;
	osTimerList[TMR_IDX_CLI_CONSOLE_SCAN].timeout_tick = CONSOLE_SCAN_TIMEOUT;
	osTimerList[TMR_IDX_CLI_CONSOLE_SCAN].timeout_cb = console_scan_timeout_cb;
	osTimerList[TMR_IDX_CLI_CONSOLE_SCAN].osTimerId = osTimerNew(osTimerList[TMR_IDX_CLI_CONSOLE_SCAN].timeout_cb, osTimerList[TMR_IDX_CLI_CONSOLE_SCAN].timeout_tick, NULL, NULL);
	assert (osTimerList[TMR_IDX_CLI_CONSOLE_SCAN].osTimerId != NULL);
	strcpy (osTimerList[TMR_IDX_CLI_CONSOLE_SCAN].timer_description, "OS_TIMER_INDEX_CLI_CONSOLE_SCAN");

	osTimerList[TMR_IDX_UPTIME_COUNT].osTimerType = osTimerPeriodic;
	osTimerList[TMR_IDX_UPTIME_COUNT].timeout_tick = UPTIME_COUNT_TIMEOUT;
	osTimerList[TMR_IDX_UPTIME_COUNT].timeout_cb = uptime_counter_timeout_cb;
	osTimerList[TMR_IDX_UPTIME_COUNT].osTimerId = osTimerNew(osTimerList[TMR_IDX_UPTIME_COUNT].timeout_cb, osTimerList[TMR_IDX_UPTIME_COUNT].timeout_tick, NULL, NULL);
	assert (osTimerList[TMR_IDX_UPTIME_COUNT].osTimerId != NULL);
	strcpy (osTimerList[TMR_IDX_UPTIME_COUNT].timer_description, "OS_TIMER_INDEX_UPTIME_COUNT");

	assert (led_act_toggle_begin() == true);
	assert (uptime_counter_begin() == true);

	return true;
}
