/**
 ******************************************************************************
  * File Name          : func_data_show.c
  * Description        : This file is generated by 위대한 송 인재 on Aug 29, 2025
 ******************************************************************************
 *
 * COPYRIGHT(c) 2024 DSN Co. Ltd.
 *
 * Redistribution and use in source and binary forms, with or without modification,
 * are permitted provided that the following conditions are met:
 *   1. Redistributions of source code must retain the above copyright notice,
 *      this list of conditions and the following disclaimer.
 *   2. Redistributions in binary form must reproduce the above copyright notice,
 *      this list of conditions and the following disclaimer in the documentation
 *      and/or other materials provided with the distribution.
 *   3. Neither the name of STMicroelectronics nor the names of its contributors
 *      may be used to endorse or promote products derived from this software
 *      without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 ******************************************************************************
 */

#include "main.h"

void func_data_show()
{
	printf (RTT_COLOR_CODE_CYAN);
	printf (CUI_ESC_CUR_HOME); osDelay(1);
	printf ("***************************************************"LINE_TERM);
	printf ("*                                                 *"LINE_TERM);
	printf ("*               Smart Bench Status                *"LINE_TERM);
	printf ("*                                                 *"LINE_TERM);
	printf ("***************************************************"LINE_TERM);
	printf (RTT_COLOR_CODE_DEFAULT);

	printf ("hw_version \t= %#010"PRIx32 LINE_TERM, SMB_StatusObj.hw_version);
	printf("fw_version \t= %s"LINE_TERM, SMB_StatusObj.fw_version);

	printf("implementer \t= Arm"LINE_TERM);
	printf("partno \t\t= Cortex-M4"LINE_TERM);

	printf ("uid0 \t\t= %#010"PRIx32 LINE_TERM, SMB_StatusObj.uid0);
	printf ("uid1 \t\t= %#010"PRIx32 LINE_TERM, SMB_StatusObj.uid1);
	printf ("uid2 \t\t= %#010"PRIx32 LINE_TERM, SMB_StatusObj.uid2);
	printf(LINE_TERM);

	// Launching date 정보 표시
	printf("Lanuching Time \t\t= %2d:%2d:%2d %s"LINE_TERM, \
			SMB_StatusObj.launchTime.Hours, SMB_StatusObj.launchTime.Minutes, SMB_StatusObj.launchTime.Seconds, (SMB_StatusObj.launchTime.Hours < 12)?"am":"pm");
	printf("Current Time \t\t= %2d:%2d:%2d %s"LINE_TERM, \
			SMB_StatusObj.currentTime.Hours, SMB_StatusObj.currentTime.Minutes, SMB_StatusObj.currentTime.Seconds, (SMB_StatusObj.currentTime.Hours < 12)?"am":"pm");
	printf ("luminance \t= 0x%02x : brightness = %s"LINE_TERM, SMB_StatusObj.smb_luminance.luminance, (SMB_StatusObj.smb_luminance.bright_or_dark == LUMINANCE_BRIGHT)?"BRIGHT":"DARK  ");
	printf ("motion \t= %s"LINE_TERM, (SMB_StatusObj.smb_motion.motion == MOTION_YES)?"MOTION_YES":"MOTION_NO");
	printf ("sonic \t= %s"LINE_TERM, (SMB_StatusObj.smb_motion.sonic_motion == SONIC_MOTION_YES)?"SONIC_MOTION_YES":"SONIC_MOTION_NO");
	printf ("luminance threshold \t= 0x%2x"LINE_TERM, SMB_StatusObj.smb_luminance.luminance_threshold);
	printf ("sonic_raw \t= 0x%04x (threshold = 0x%04x)"LINE_TERM, SMB_StatusObj.smb_motion.sonic_raw_data, SMB_StatusObj.smb_motion.sonic_threshold);
	printf ("sonic_distance \t= %d cm  "LINE_TERM, ((SMB_StatusObj.smb_motion.sonic_raw_data * 17) / 200));
	printf(LINE_TERM);

	printf("YUI \t\t= %4d mV  ", SMB_adc_value.YUI);
	printf("(raw = %4d)"LINE_TERM, SMB_adc_value.yui_raw_data);
	printf("MUI1 \t\t= %4d mV  ", SMB_adc_value.MUI1);
	printf("(raw = %4d)"LINE_TERM, SMB_adc_value.mui1_raw_data);
	printf("MUI2 \t\t= %4d mV  ", SMB_adc_value.MUI2);
	printf("(raw = %4d)"LINE_TERM, SMB_adc_value.mui2_raw_data);
	printf("AEDT \t\t= %4d do  ", SMB_adc_value.AEDT);
	printf("(raw = %4d)"LINE_TERM, SMB_adc_value.aedt_raw_data);
	printf("CDS \t\t= %4d mV  ", SMB_adc_value.CDS);
	printf("(raw = %4d)"LINE_TERM, SMB_adc_value.cds_raw_data);

	printf("TEMP \t\t= %4d do"LINE_TERM, SMB_adc_value.TEMP);
	printf("VBAT \t\t= %4d mV"LINE_TERM, SMB_adc_value.VBAT);
	printf("VREF \t\t= %4d mV"LINE_TERM, SMB_adc_value.VREF);

	printf(LINE_TERM);

	printf ("LTE \t\t= %s"LINE_TERM, (SMB_ControlObj.lteObj.lte_on_off_flag == LTE_OFF)?"LTE_OFF":"LTE_ON ");
	printf ("FAN \t\t= %s"LINE_TERM, (SMB_ControlObj.fanObj.fan_on_off_flag == FAN_OFF)?"FAN_OFF":"FAN_ON ");
	printf ("YUCHAR \t\t= %s"LINE_TERM, (SMB_ControlObj.yucharObj.yuchar_on_off_flag == YUCHAR_OFF)?"YUCHAR_OFF":"YUCHAR_ON ");
	printf ("MUCHAR1 \t= %s"LINE_TERM, (SMB_ControlObj.muchar1Obj.muchar1_on_off_flag == MUCHAR1_OFF)?"MUCHAR1_OFF":"MUCHAR1_ON ");
	printf ("MUCHAR2 \t= %s"LINE_TERM, (SMB_ControlObj.muchar2Obj.muchar2_on_off_flag == MUCHAR2_OFF)?"MUCHAR2_OFF":"MUCHAR2_ON ");
	printf ("INVERTER \t= %s"LINE_TERM, (SMB_ControlObj.inverterObj.inverter_on_off_flag == INVERTER_OFF)?"INVERTER_OFF":"INVERTER_ON ");
	printf ("SIREN \t\t= %s"LINE_TERM, (SMB_ControlObj.sirenObj.siren_on_off_flag == SIREN_OFF)?"SIREN_OFF":"SIREN_ON ");
	printf ("SPEAKER \t= %s"LINE_TERM, (SMB_ControlObj.speakerObj.speaker_on_off_flag == SPEAKER_OFF)?"SPEAKER_OFF":"SPEAKER_ON ");
	printf("LEDBAR \t\t= ");
	switch (SMB_ControlObj.ledbarObj.ledbar_color) {
	case LEDBAR_OFF :	printf("OFF   "LINE_TERM); break;
	case LEDBAR_RED :	printf("RED   "LINE_TERM); break;
	case LEDBAR_GREEN :	printf("GREEN "LINE_TERM); break;
	case LEDBAR_BLUE :	printf("BLUE  "LINE_TERM); break;
	case LEDBAR_WHITE :	printf("WHITE "LINE_TERM); break;
	case LEDBAR_YELLOW :printf("YELLOW"LINE_TERM); break;
	}

#if 0
	printf ("Emer. Button \t= %s"LINE_TERM, (SBStatusObj.emegency_btn == EMER_BTN_PRESSED)?"PRESSED ":"RELEASED");
	printf ("AED Door \t= %s"LINE_TERM, (SBStatusObj.aed_door == AED_DOOR_OPEN)?"OPEN  ":"CLOSED");
	printf ("FIRE Door \t= %s"LINE_TERM, (SBStatusObj.fire_door == FIRE_DOOR_OPEN)?"OPEN  ":"CLOSED");
	printf ("Flooding \t= %s"LINE_TERM, (SBStatusObj.flooding == FLOOD_HAPPEN)?"WATER":"DRY  ");
	printf ("LAMP \t\t= %s"LINE_TERM, (lampObj.lamp_on_off == LAMP_OFF)?"OFF":"ON ");


	printf("lamp_off_duty \t= %02d:%02d %s"LINE_TERM, \
			SBConfigObj.lamp_off_duty.Hours, SBConfigObj.lamp_off_duty.Minutes, (SBConfigObj.lamp_off_duty.Hours < 12)?"am":"pm");
	printf("lamp_on_duty \t= %02d:%02d %s"LINE_TERM, \
			SBConfigObj.lamp_on_duty.Hours, SBConfigObj.lamp_on_duty.Minutes, (SBConfigObj.lamp_on_duty.Hours < 12)?"am":"pm");
	printf("lamp_duty \t= %s"LINE_TERM, (lamp_duty_check() == LAMP_DUTY_ON)?"LAMP_DUTY_ON ":"LAMP_DUTY_OFF");
	printf ("siren_on_time \t= %ld (sec)"LINE_TERM, sirenObj.siren_on_time);
	printf ("motion_latency \t= %ld (sec)"LINE_TERM, SBConfigObj.motion_latency);
	printf("Raspberry work \t= %s"LINE_TERM, (SBStatusObj.rb_working == true)?"YES ":"NO ");
#endif

	{
		uint8_t day, hour, min, sec;
		uint64_t tmp;
		tmp = SMB_StatusObj.uptime_counter;

		day = tmp /DAY_TO_SEC;
		tmp = tmp - (day*DAY_TO_SEC);

		hour = tmp/HOUR_TO_SEC;
		tmp = tmp - (hour*HOUR_TO_SEC);

		min = tmp/MIN_TO_SEC;
		tmp = tmp - (min*MIN_TO_SEC);

		sec = tmp;
		printf(LINE_TERM"Uptime : %d days, %d hours, %d mins, %d sec"LINE_TERM, day, hour, min, sec);
	}
}
