/**
 ******************************************************************************
 * File Name          : func_misc.c
 * Description        : This file is generated by 위대한 송 인재.
 ******************************************************************************
 *
 * COPYRIGHT(c) 2024 LMS Co. Ltd.
 *
 * Redistribution and use in source and binary forms, with or without modification,
 * are permitted provided that the following conditions are met:
 *   1. Redistributions of source code must retain the above copyright notice,
 *      this list of conditions and the following disclaimer.
 *   2. Redistributions in binary form must reproduce the above copyright notice,
 *      this list of conditions and the following disclaimer in the documentation
 *      and/or other materials provided with the distribution.
 *   3. Neither the name of STMicroelectronics nor the names of its contributors
 *      may be used to endorse or promote products derived from this software
 *      without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 ******************************************************************************
 */

#include "main.h"

void hexDump (SYS_CMD_DEVICE_NODE* pCmdIO, uint32_t nominal_addr, void *addr, uint32_t len)
{
	const void* cmdIoParam = pCmdIO->cmdIoParam;
	uint32_t i;
	unsigned char buff[17];       // stores the ASCII data
	unsigned char *pc = addr;     // cast to make the code cleaner.

	for (i = 0; i < len; i++) {
		if ((i % 16) == 0) {
			if (i != 0)	{
				(*pCmdIO->pCmdApi->print)(cmdIoParam, "  %s"LINE_TERM, buff);
				osDelay(10);	// print buffer 가 넘쳐서 깨지는 것 때문에 이정도는 줘야 안깨지더라..
			}

			(*pCmdIO->pCmdApi->print)(cmdIoParam, "%8X ", (uint32_t)nominal_addr+i);
		}

		(*pCmdIO->pCmdApi->print)(cmdIoParam, " %02X", pc[i]);

		if ((pc[i] < 0x20) || (pc[i] > 0x7e)) buff[i % 16] = '.';
		else buff[i % 16] = pc[i];
		buff[(i % 16) + 1] = '\0';
	}

	while ((i % 16) != 0) {
		(*pCmdIO->pCmdApi->msg)(cmdIoParam, "   ");
		i++;
	}

	(*pCmdIO->pCmdApi->print)(cmdIoParam, "  %s"LINE_TERM, buff);
}

void HexDump (uint32_t nominal_addr, void *addr, uint32_t len)
{
	uint32_t i;
	unsigned char buff[17];       // stores the ASCII data
	unsigned char *pc = addr;     // cast to make the code cleaner.

	for (i = 0; i < len; i++) {
		if ((i % 16) == 0) {
			if (i != 0)	{
				printf("  %s"LINE_TERM, buff);
				osDelay(10);	// print buffer 가 넘쳐서 깨지는 것 때문에 이정도는 줘야 안깨지더라..
			}

			printf("0x%08lX ", (uint32_t)(nominal_addr+i));
		}

		printf(" %02X", pc[i]);

		if ((pc[i] < 0x20) || (pc[i] > 0x7e)) buff[i % 16] = '.';
		else buff[i % 16] = pc[i];
		buff[(i % 16) + 1] = '\0';
	}

	while ((i % 16) != 0) {
		printf("   ");
		i++;
	}

	printf("  %s"LINE_TERM, buff);
}

bool duty_minutes_set(SMB_StatusObj_t *sp)
{
//	RTC_TimeTypeDef sTime = {0};
//
//	sp->minutes_off_duty = SBConfigObj.lamp_off_duty.Hours * 60 + SBConfigObj.lamp_off_duty.Minutes;
//	sp->minutes_on_duty = SBConfigObj.lamp_on_duty.Hours * 60 + SBConfigObj.lamp_on_duty.Minutes;
//	if (sp->minutes_off_duty == sp->minutes_on_duty) {
//		printf("%s() : sp->minutes_off_duty == sp->minutes_on_duty"LINE_TERM, __FUNCTION__);
//	}
//	if (sp->minutes_off_duty < sp->minutes_on_duty) sp->off_duty_1st = true;
//	else sp->off_duty_1st = false;
//	assert (HAL_RTC_GetTime(&hrtc, &sTime, RTC_FORMAT_BIN) == HAL_OK);
//	sp->minutes_current = sTime.Hours * 60 + sTime.Minutes;

	return true;
}
