/**
 ******************************************************************************
  * File Name          : func_config.c
  * Description        : This file is generated by 위대한 송 인재 on Aug 24, 2025
 ******************************************************************************
 *
 * COPYRIGHT(c) 2024 DSN Co. Ltd.
 *
 * Redistribution and use in source and binary forms, with or without modification,
 * are permitted provided that the following conditions are met:
 *   1. Redistributions of source code must retain the above copyright notice,
 *      this list of conditions and the following disclaimer.
 *   2. Redistributions in binary form must reproduce the above copyright notice,
 *      this list of conditions and the following disclaimer in the documentation
 *      and/or other materials provided with the distribution.
 *   3. Neither the name of STMicroelectronics nor the names of its contributors
 *      may be used to endorse or promote products derived from this software
 *      without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 ******************************************************************************
 */

#include "main.h"

const SMB_ConfigObj_t SMBConfig_fac_default = {
		.work_mode = SMB_MODE_NETWORK,
		.banner = BANNER_DSN,
		.machine_serial_no = 12345678,
		.site_address = "#630, Gunpocheomdansaneop 2-ro 7 beon-gil, Gunpo-si, Gyeonggi-do, Korea",
		.install_worker = "Daeshin Networks Co., Ltd",
		.install_Date.WeekDay = 7,
		.install_Date.Date = 6,
		.install_Date.Month = 3,
		.install_Date.Year = 5,
		.manufacture_Date.WeekDay = 7,
		.manufacture_Date.Date = 6,
		.manufacture_Date.Month = 3,
		.manufacture_Date.Year = 5,
		.fw_update_Date.WeekDay = 7,
		.fw_update_Date.Date = 6,
		.fw_update_Date.Month = 3,
		.fw_update_Date.Year = 5,
		.running_fw = "Installed at Factory",

		.bright_dark_boundary = 0x80,			// LUMINANCE_BRIGHT or LUMINANCE_DARK 를 판단하는 IMS 센서값의 기준을 임의로 정함. 현장에서 설치한 후에 결정해야 함..
		.sonic_threshold = 160,				// Sonic value 를 이용해서 사람이 있는지 없는지를 판단하는 초음파 센서값 (cm 단위)의 기준.

		.motion_latency = 30,		// 움직임이 감지된 후 motion 이 있다고 판단하는 지연시간 (sec)
		.lamp_off_duty.Hours = 10,
		.lamp_off_duty.Minutes = 0,
		.lamp_off_duty.Seconds = 0,
		.lamp_off_duty.TimeFormat = RTC_HOURFORMAT_24,
		.lamp_on_duty.Hours = 18,
		.lamp_on_duty.Minutes = 0,
		.lamp_on_duty.Seconds = 0,
		.lamp_on_duty.TimeFormat = RTC_HOURFORMAT_24,
		.siren_on_time = 30,

		.aedt_high_mark = 35,
		.aedt_normal_high = 25,
		.aedt_normal_low = 10,
		.aedt_low_mark = 0,
		.show_flag = 0,
};

bool get_SMB_config (SMB_ConfigObj_t *pconfig)
{
	struct lfs_info info;
	lfs_file_t file;
	uint32_t stored_crc, calculated_crc;

	if (IsFS_mount != true) {
		printf("File system mount first!!"LINE_TERM);
		return false;
	}

	if (lfs_stat(&lfs, CONFIG_FILE_NAME, &info) != LFS_ERR_OK) {
		printf("NO file %s !!"LINE_TERM, CONFIG_FILE_NAME);
		return false;
	}

	assert (lfs_file_open(&lfs, &file, CONFIG_FILE_NAME, LFS_O_RDONLY) == LFS_ERR_OK);
	assert (lfs_file_read(&lfs, &file, (void *)pconfig, info.size) == info.size);
	assert (lfs_file_close(&lfs, &file) == LFS_ERR_OK);

	assert (HAL_CRC_GetState(&hcrc)== HAL_CRC_STATE_READY);
	calculated_crc = HAL_CRC_Calculate(&hcrc, (uint32_t *)pconfig, info.size);
//	printf("%s() calculated_crc = %lx"LINE_TERM, __FUNCTION__, calculated_crc);

	if (lfs_stat(&lfs, CONFIG_CRC_FILE_NAME, &info) != LFS_ERR_OK) {
		printf("NO CRC file %s !!"LINE_TERM, CONFIG_CRC_FILE_NAME);
		return false;
	}

	assert (lfs_file_open(&lfs, &file, CONFIG_CRC_FILE_NAME, LFS_O_RDONLY) == LFS_ERR_OK);
	assert (lfs_file_read(&lfs, &file, &stored_crc, info.size) == info.size);
	assert (lfs_file_close(&lfs, &file) == LFS_ERR_OK);
//	printf("%s() stored_crc = %lx"LINE_TERM, __FUNCTION__, stored_crc);

	if (stored_crc != calculated_crc) return false;
	else return true;
}

bool get_factory_default (SMB_ConfigObj_t *pconfig)
{
	memcpy ((void *)pconfig, (void *)&SMBConfig_fac_default, sizeof(SMBConfig_fac_default));
	return true;
}


