/**
 ******************************************************************************
 * File Name          : func_greeting.c
 * Description        : This file is generated by 위대한 송 인재.
 ******************************************************************************
 *
 * COPYRIGHT(c) 2024 LMS Co. Ltd.
 *
 * Redistribution and use in source and binary forms, with or without modification,
 * are permitted provided that the following conditions are met:
 *   1. Redistributions of source code must retain the above copyright notice,
 *      this list of conditions and the following disclaimer.
 *   2. Redistributions in binary form must reproduce the above copyright notice,
 *      this list of conditions and the following disclaimer in the documentation
 *      and/or other materials provided with the distribution.
 *   3. Neither the name of STMicroelectronics nor the names of its contributors
 *      may be used to endorse or promote products derived from this software
 *      without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 ******************************************************************************
 */

#include "main.h"

void show_banner_dsn(void)
{
	printf (LINE_TERM "8 888888888o.         d888888o.   b.             8    ");
	printf (LINE_TERM "8 8888    `^888.    .`8888:' `88. 888o.          8    ");
	printf (LINE_TERM "8 8888        `88.  8.`8888.   Y8 Y88888o.       8    ");
	printf (LINE_TERM "8 8888         `88  `8.`8888.     .`Y888888o.    8    ");
	printf (LINE_TERM "8 8888          88   `8.`8888.    8o. `Y888888o. 8    ");
	printf (LINE_TERM "8 8888          88    `8.`8888.   8`Y8o. `Y88888o8    ");
	printf (LINE_TERM "8 8888         ,88     `8.`8888.  8   `Y8o. `Y8888    ");
	printf (LINE_TERM "8 8888        ,88' 8b   `8.`8888. 8      `Y8o. `Y8    ");
	printf (LINE_TERM "8 8888    ,o88P'   `8b.  ;8.`8888 8         `Y8o.`    ");
	printf (LINE_TERM "8 888888888P'       `Y8888P ,88P' 8            `Yo    ");
}

void show_banner_smart(void)
{
	printf (LINE_TERM "	   d888888o.            ,8.       ,8.                   .8.          8 888888888o.   8888888 8888888888	");
	printf (LINE_TERM "	 .`8888:' `88.         ,888.     ,888.                 .888.         8 8888    `88.        8 8888		");
	printf (LINE_TERM "	 8.`8888.   Y8        .`8888.   .`8888.               :88888.        8 8888     `88        8 8888		");
	printf (LINE_TERM "	 `8.`8888.           ,8.`8888. ,8.`8888.             . `88888.       8 8888     ,88        8 8888		");
	printf (LINE_TERM "	  `8.`8888.         ,8'8.`8888,8^8.`8888.           .8. `88888.      8 8888.   ,88'        8 8888		");
	printf (LINE_TERM "	   `8.`8888.       ,8' `8.`8888' `8.`8888.         .8`8. `88888.     8 888888888P'         8 8888		");
	printf (LINE_TERM "	    `8.`8888.     ,8'   `8.`88'   `8.`8888.       .8' `8. `88888.    8 8888`8b             8 8888		");
	printf (LINE_TERM "	8b   `8.`8888.   ,8'     `8.`'     `8.`8888.     .8'   `8. `88888.   8 8888 `8b.           8 8888		");
	printf (LINE_TERM "	`8b.  ;8.`8888  ,8'       `8        `8.`8888.   .888888888. `88888.  8 8888   `8b.         8 8888		");
	printf (LINE_TERM "	 `Y8888P ,88P' ,8'         `         `8.`8888. .8'       `8. `88888. 8 8888     `88.       8 8888		");
}

void show_banner_bench(void)
{
	printf (LINE_TERM "8 888888888o   8 8888888888   b.             8     ,o888888o.    8 8888        8	");
	printf (LINE_TERM "8 8888    `88. 8 8888         888o.          8    8888     `88.  8 8888        8	");
	printf (LINE_TERM "8 8888     `88 8 8888         Y88888o.       8 ,8 8888       `8. 8 8888        8	");
	printf (LINE_TERM "8 8888     ,88 8 8888         .`Y888888o.    8 88 8888           8 8888        8	");
	printf (LINE_TERM "8 8888.   ,88' 8 888888888888 8o. `Y888888o. 8 88 8888           8 8888        8	");
	printf (LINE_TERM "8 8888888888   8 8888         8`Y8o. `Y88888o8 88 8888           8 8888        8	");
	printf (LINE_TERM "8 8888    `88. 8 8888         8   `Y8o. `Y8888 88 8888           8 8888888888888	");
	printf (LINE_TERM "8 8888      88 8 8888         8      `Y8o. `Y8 `8 8888       .8' 8 8888        8	");
	printf (LINE_TERM "8 8888    ,88' 8 8888         8         `Y8o.`    8888     ,88'  8 8888        8	");
	printf (LINE_TERM "8 888888888P   8 888888888888 8            `Yo     `8888888P'    8 8888        8	");
}

void show_banner_pee(void)
{
	printf (LINE_TERM "8 888888888o   8 8888888888   8 8888888888       ");
	printf (LINE_TERM "8 8888    `88. 8 8888         8 8888             ");
	printf (LINE_TERM "8 8888     `88 8 8888         8 8888             ");
	printf (LINE_TERM "8 8888     ,88 8 8888         8 8888             ");
	printf (LINE_TERM "8 8888.   ,88' 8 888888888888 8 888888888888     ");
	printf (LINE_TERM "8 888888888P'  8 8888         8 8888             ");
	printf (LINE_TERM "8 8888         8 8888         8 8888             ");
	printf (LINE_TERM "8 8888         8 8888         8 8888             ");
	printf (LINE_TERM "8 8888         8 8888         8 8888             ");
	printf (LINE_TERM "8 8888         8 888888888888 8 888888888888     ");
}

void show_banner_shit(void)
{
	printf (LINE_TERM "   d888888o.   8 8888        8  8 8888 8888888 8888888888         ");
	printf (LINE_TERM " .`8888:' `88. 8 8888        8  8 8888       8 8888               ");
	printf (LINE_TERM " 8.`8888.   Y8 8 8888        8  8 8888       8 8888               ");
	printf (LINE_TERM " `8.`8888.     8 8888        8  8 8888       8 8888               ");
	printf (LINE_TERM "  `8.`8888.    8 8888        8  8 8888       8 8888               ");
	printf (LINE_TERM "   `8.`8888.   8 8888        8  8 8888       8 8888               ");
	printf (LINE_TERM "    `8.`8888.  8 8888888888888  8 8888       8 8888               ");
	printf (LINE_TERM "8b   `8.`8888. 8 8888        8  8 8888       8 8888               ");
	printf (LINE_TERM "`8b.  ;8.`8888 8 8888        8  8 8888       8 8888               ");
	printf (LINE_TERM " `Y8888P ,88P' 8 8888        8  8 8888       8 8888               ");
}

void show_banner_ballet(void)
{
	printf (LINE_TERM "                                  .,"); HAL_Delay(1);
	printf (LINE_TERM "                                  $."); HAL_Delay(1);
	printf (LINE_TERM "                                  =*.                   .**;-          :**."); HAL_Delay(1);
	printf (LINE_TERM "                          :.:     =.                   ;=$::-         .:=$$=."); HAL_Delay(1);
	printf (LINE_TERM "                          ~==:   ~*                   =* -!                *;"); HAL_Delay(1);
	printf (LINE_TERM "                            *$  ~ =.                 !=:                   .="); HAL_Delay(1);
	printf (LINE_TERM "                             $ $==~=,               -=$                    .=~       *!"); HAL_Delay(1);
	printf (LINE_TERM "                            ,$ $=!-=;               ==,                    .=:      !==."); HAL_Delay(1);
	printf (LINE_TERM "           ,                *=~===*!=;              =$,   ,**.              *=     -$=$."); HAL_Delay(1);
	printf (LINE_TERM "          ;=$.              *=$===$.$;              ==, -$===$              *=-    ====."); HAL_Delay(1);
	printf (LINE_TERM "        *====.              *:-====.=;              *=, ======~             .==   ,====$"); HAL_Delay(1);
	printf (LINE_TERM "       !=====;,             *$ ====.=;              -=-.;=====,              ;=:  -===$."); HAL_Delay(1);
	printf (LINE_TERM "       =======$,,,,,        ;=* *==.=;              -=$.-=**=-                ==- -==$;"); HAL_Delay(1);
	printf (LINE_TERM "       $====.=======         $=! :=$=;              -=====-===                -== ==$"); HAL_Delay(1);
	printf (LINE_TERM "       .$==;=========        ,==$====;               =====-:=-                 $===="); HAL_Delay(1);
	printf (LINE_TERM "        :$;==========;        ;=======~             ;=====$~                   =====;-"); HAL_Delay(1);
	printf (LINE_TERM "        =$==*=!=======.        *======*            ;========:                 -=======-"); HAL_Delay(1);
	printf (LINE_TERM "       ;===$=:. $=====;         !$=====            :=========.                ;====$$==$"); HAL_Delay(1);
	printf (LINE_TERM "     ,==*==-  !;;*;===;          ~====*            .======.;=$-               -=====.:=$*"); HAL_Delay(1);
	printf (LINE_TERM "    ,==$;  ~*=========;           !===*            -=====   ;==.              ,===$:  .:$*~"); HAL_Delay(1);
	printf (LINE_TERM "   .=*-~$.  ==========;      .~$=======            ;===$.,.  !=!,              ===$     ;*$=-."); HAL_Delay(1);
	printf (LINE_TERM "   =~  $~.   .========;     .===========           ~========*=!=$=            ,$====*=,   ,===-"); HAL_Delay(1);
	printf (LINE_TERM "  :=~  =.    ~========$;   ;============$~        ;*==========~.~:$;:      .;$==========!~  ,-$!"); HAL_Delay(1);
	printf (LINE_TERM "  *!!  **     ;=========. -;==============$.    .;============~    ,;;!~  ,================    !!"); HAL_Delay(1);
	printf (LINE_TERM "  *~.  ,;     :=========$    ~=============,    :=============         ;. $===============*    !~"); HAL_Delay(1);
	printf (LINE_TERM "  *=            .========~   ..============    .===========$$.           ;=================    . !"); HAL_Delay(1);
	printf (LINE_TERM "  -,             ========:     $=========-~    !=$=========!~           ;$==============;-       -"); HAL_Delay(1);
	printf (LINE_TERM "                $=========     .====$==~;      =*!======= :             ,-,.*==========;!    "); HAL_Delay(1);
	printf (LINE_TERM "               .====$====-      ====$=.             $===$                     ===$====:"); HAL_Delay(1);
	printf (LINE_TERM "               -===;,$:-,       !=====              ====!.                     $=====;"); HAL_Delay(1);
	printf (LINE_TERM "               ~==*~            !==$**              ===!=,                     -=$==="); HAL_Delay(1);
	printf (LINE_TERM "               $==!              ===;;              ===*=:                      =$==*"); HAL_Delay(1);
	printf (LINE_TERM "               ==$~              ===;               ======                      !$==-"); HAL_Delay(1);
	printf (LINE_TERM "              :===               :$=,               ==,:==-                     ,==="); HAL_Delay(1);
	printf (LINE_TERM "             :*=~.               ,==-              ~==, ;=$                      ==!"); HAL_Delay(1);
	printf (LINE_TERM "            ~$=*!                :==~              ;==  ,==!                     !=!"); HAL_Delay(1);
	printf (LINE_TERM "           ~$==!                 $$=~              ===   $==                     =$$"); HAL_Delay(1);
	printf (LINE_TERM "           ===*,                .=$=*             ~==,    ==*                    =$=-"); HAL_Delay(1);
	printf (LINE_TERM "           ==$;                 !$;=$             *=*     ;=*                   ,===*"); HAL_Delay(1);
	printf (LINE_TERM "           ==$,                 !====            .==.      $=.                  *=*=$"); HAL_Delay(1);
	printf (LINE_TERM "          ;===                  !=*==.           .=~       ~$.                  !$,=="); HAL_Delay(1);
	printf (LINE_TERM "          !=-,                  != ,=;           =!        ,=.                  !; =="); HAL_Delay(1);
	printf (LINE_TERM "          !==                   !=  *;          ~=.         =~                  $: =="); HAL_Delay(1);
	printf (LINE_TERM "          !!=                   !$  ;*          $*          $$-                 =  =="); HAL_Delay(1);
	printf (LINE_TERM "          ;$=                   ==  ;=          =*          :==                ;=  -=:"); HAL_Delay(1);
	printf (LINE_TERM "         ==**                  $=;  ;=         ;=*          ,==                ==   $;"); HAL_Delay(1);
	printf (LINE_TERM "         :=$                    =:  ;==        !=*          ,=~                $=   ="); HAL_Delay(1);
	printf (LINE_TERM "         .==                    !:  ;==        !=*          .=~                $=   ="); HAL_Delay(1);
	printf (LINE_TERM "         =$;                    !:  ;==        ;=*           =~                ==   $"); HAL_Delay(1);
	printf (LINE_TERM "        .=~                     ~~   ;-        ,=-           -:"); HAL_Delay(1);
}

void Greeting(void)
{

	if (READ_BIT(SYSCFG->MEMRMP, SYSCFG_MEMRMP_FB_MODE) == 0 ) {
		printf (RTT_COLOR_CODE_CYAN);
	}
	else {
		printf (RTT_COLOR_CODE_LIGHT_YELLOW);
	}

	switch (SMB_ConfigObj.banner) {
	case BANNER_DSN :		show_banner_dsn(); break;
	case BANNER_SMART :		show_banner_smart(); break;
	case BANNER_BENCH :		show_banner_bench(); break;
	case BANNER_PEE :		show_banner_pee(); break;
	case BANNER_SHIT :		show_banner_shit(); break;
	case BANNER_BALLET :	show_banner_ballet(); break;
	default : break;
	}

	printf (RTT_COLOR_CODE_DEFAULT);
	printf (LINE_TERM);
	printf (LINE_TERM "Have a GoooooooooooooooooooooD day !!"LINE_TERM);
	printf (RTT_COLOR_CODE_BOLD_CYAN);
	printf (LINE_TERM "firmware version = %s", SMB_StatusObj.fw_version);
	printf (RTT_COLOR_CODE_DEFAULT);
	printf (RTT_COLOR_LIGHT_WHITE);
	printf (LINE_TERM);

	return;
}
