/**
 ******************************************************************************
  * File Name          : func_timer_list.c
  * Description        : This file is generated by 위대한 송 인재 on Aug 8, 2025
 ******************************************************************************
 *
 * COPYRIGHT(c) 2024 DSN Co. Ltd.
 *
 * Redistribution and use in source and binary forms, with or without modification,
 * are permitted provided that the following conditions are met:
 *   1. Redistributions of source code must retain the above copyright notice,
 *      this list of conditions and the following disclaimer.
 *   2. Redistributions in binary form must reproduce the above copyright notice,
 *      this list of conditions and the following disclaimer in the documentation
 *      and/or other materials provided with the distribution.
 *   3. Neither the name of STMicroelectronics nor the names of its contributors
 *      may be used to endorse or promote products derived from this software
 *      without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 ******************************************************************************
 */

#include "main.h"

extern osMessageQueueId_t		managerThreadQ;

static void led_act_toggle_timeout_cb (void *arg)
{
	led_act_toggle;
	led_com_off;
}

static bool led_act_toggle_begin()
{
	assert (osTimerList[TMR_IDX_LED_ACT_TOGGLE].osTimerId != NULL);
	assert (osTimerStart(osTimerList[TMR_IDX_LED_ACT_TOGGLE].osTimerId, LED_ACT_TOGGLE_TIMEOUT) == osOK);

	return true;
}

static void console_scan_timeout_cb (void *arg)
{
	osThreadFlagsSet(Thread_CLI_Handler, EF_CONSOLE_SCAN);
}

static void uptime_counter_timeout_cb (void *arg)
{
	SMB_StatusObj.uptime_counter++;
	assert (HAL_RTC_GetTime(&hrtc, &SMB_StatusObj.currentTime, RTC_FORMAT_BCD) == HAL_OK);
	assert (HAL_RTC_GetDate(&hrtc, &SMB_StatusObj.currentDate, RTC_FORMAT_BCD) == HAL_OK);
}

static bool uptime_counter_begin()
{
	assert (osTimerList[TMR_IDX_UPTIME_COUNT].osTimerId != NULL);
	assert (osTimerStart(osTimerList[TMR_IDX_UPTIME_COUNT].osTimerId, UPTIME_COUNT_TIMEOUT) == osOK);

	return true;
}

static void smb_adc_read_cb (void *arg)
{
	manager_msg_t manager_msg;

	memset (&manager_msg, 0, sizeof(manager_msg));
	manager_msg.head.type = MANAGER_MSG_ADC_READ;
	manager_msg.head.dst = WORKM_MANAGER;
	manager_msg.head.src = WORKM_TIMER;
	manager_msg.head.len = sizeof(manager_msg.head);

	osMessageQueuePut(managerThreadQ, &manager_msg, 0U, 0U);
}

static void smb_data_show_cb (void *arg)
{
	manager_msg_t manager_msg;

	memset (&manager_msg, 0, sizeof(manager_msg));
	manager_msg.head.type = MANAGER_MSG_DATA_SHOW;
	manager_msg.head.dst = WORKM_MANAGER;
	manager_msg.head.src = WORKM_TIMER;
	manager_msg.head.len = sizeof(manager_msg.head);

	osMessageQueuePut(managerThreadQ, &manager_msg, 0U, 0U);
}

static void smb_status_report_cb (void *arg)
{
	rb_msg_t rb_msg;

	memset (&rb_msg, 0, sizeof(rb_msg));

	rb_msg.head.type = RB_MSG_COMMAND;
	rb_msg.head.dst = WORKM_RB;
	rb_msg.head.src = WORKM_RB;
	rb_msg.head.len = RBERRY_MSG_LENGTH;

	rb_msg.rb_command.type = RB_REPORT_SENSOR_STATUS;
	rb_msg.rb_command.len = 0;
	rb_msg.rb_command.checksum = checksum((uint8_t *)&rb_msg.rb_command, 6);
	rb_msg.rb_command.end_marker = END_MARKER;

	osMessageQueuePut(rbThreadQ, &rb_msg, 0U, 0U);
}

static void SOH_req_timeout_cb (void *arg)
{
	iap_msg_t iap_msg;

	memset (&iap_msg, 0, sizeof(iap_msg));

	iap_msg.head.type = IAP_MSG_SOH_REQ_TIMEOUT;
	iap_msg.head.dst = WORKM_IAP;
	iap_msg.head.src = WORKM_UART4;
	iap_msg.head.len = 0;

	iap_msg.body.mpool = NULL;
	osMessageQueuePut(iapThreadQ, &iap_msg, 0U, 0U);
}

static void SMB_manipulation_timeout_cb (void *arg)
{
	printf("%s()"LINE_TERM, __FUNCTION__);
	SMB_StatusObj.smb_manipulation = false;
	SMB_ManiObj_restore(&SMB_ManiObj, &SMB_ControlObj);
}

bool osTimerList_init(osTimerEntry_t osTimerList[])
{
	for (uint32_t i = TMR_IDX_BEGIN ; i < TMR_IDX_END ; i++) {
		osTimerList[i].osTimerId_t = NULL;
		osTimerList[i].osTimerType = osTimerOnce;
		osTimerList[i].timeout_tick = 0;
		osTimerList[i].timeout_cb = NULL;
		strcpy (osTimerList[i].timer_description, "UNDEFINED TIMER");
	}

	osTimerList[TMR_IDX_LED_ACT_TOGGLE].osTimerType = osTimerPeriodic;
	osTimerList[TMR_IDX_LED_ACT_TOGGLE].timeout_tick = LED_ACT_TOGGLE_TIMEOUT;
	osTimerList[TMR_IDX_LED_ACT_TOGGLE].timeout_cb = led_act_toggle_timeout_cb;
	osTimerList[TMR_IDX_LED_ACT_TOGGLE].osTimerId = osTimerNew(osTimerList[TMR_IDX_LED_ACT_TOGGLE].timeout_cb, osTimerList[TMR_IDX_LED_ACT_TOGGLE].osTimerType, NULL, NULL);
	assert (osTimerList[TMR_IDX_LED_ACT_TOGGLE].osTimerId != NULL);
	strcpy (osTimerList[TMR_IDX_LED_ACT_TOGGLE].timer_description, "OS_TIMER_INDEX_LED_ACT_TOGGLE");

	osTimerList[TMR_IDX_CLI_CONSOLE_SCAN].osTimerType = osTimerPeriodic;
	osTimerList[TMR_IDX_CLI_CONSOLE_SCAN].timeout_tick = CONSOLE_SCAN_TIMEOUT;
	osTimerList[TMR_IDX_CLI_CONSOLE_SCAN].timeout_cb = console_scan_timeout_cb;
	osTimerList[TMR_IDX_CLI_CONSOLE_SCAN].osTimerId = osTimerNew(osTimerList[TMR_IDX_CLI_CONSOLE_SCAN].timeout_cb, osTimerList[TMR_IDX_CLI_CONSOLE_SCAN].osTimerType, NULL, NULL);
	assert (osTimerList[TMR_IDX_CLI_CONSOLE_SCAN].osTimerId != NULL);
	strcpy (osTimerList[TMR_IDX_CLI_CONSOLE_SCAN].timer_description, "OS_TIMER_INDEX_CLI_CONSOLE_SCAN");

	osTimerList[TMR_IDX_UPTIME_COUNT].osTimerType = osTimerPeriodic;
	osTimerList[TMR_IDX_UPTIME_COUNT].timeout_tick = UPTIME_COUNT_TIMEOUT;
	osTimerList[TMR_IDX_UPTIME_COUNT].timeout_cb = uptime_counter_timeout_cb;
	osTimerList[TMR_IDX_UPTIME_COUNT].osTimerId = osTimerNew(osTimerList[TMR_IDX_UPTIME_COUNT].timeout_cb, osTimerList[TMR_IDX_UPTIME_COUNT].osTimerType, NULL, NULL);
	assert (osTimerList[TMR_IDX_UPTIME_COUNT].osTimerId != NULL);
	strcpy (osTimerList[TMR_IDX_UPTIME_COUNT].timer_description, "OS_TIMER_INDEX_UPTIME_COUNT");

	osTimerList[TMR_IDX_ADC_READ].osTimerType = osTimerPeriodic;
	osTimerList[TMR_IDX_ADC_READ].timeout_tick = SMB_ADC_READ_TIMEOUT;
	osTimerList[TMR_IDX_ADC_READ].timeout_cb = smb_adc_read_cb;
	osTimerList[TMR_IDX_ADC_READ].osTimerId = osTimerNew(osTimerList[TMR_IDX_ADC_READ].timeout_cb, osTimerList[TMR_IDX_ADC_READ].osTimerType, NULL, NULL);
	assert (osTimerList[TMR_IDX_ADC_READ].osTimerId != NULL);
	strcpy (osTimerList[TMR_IDX_ADC_READ].timer_description, "TMR_IDX_ADC_READ");

	osTimerList[TMR_IDX_SMB_DATA_SHOW].osTimerType = osTimerPeriodic;
	osTimerList[TMR_IDX_SMB_DATA_SHOW].timeout_tick = SMB_DATA_SHOW_TIMEOUT;
	osTimerList[TMR_IDX_SMB_DATA_SHOW].timeout_cb = smb_data_show_cb;
	osTimerList[TMR_IDX_SMB_DATA_SHOW].osTimerId = osTimerNew(osTimerList[TMR_IDX_SMB_DATA_SHOW].timeout_cb, osTimerList[TMR_IDX_SMB_DATA_SHOW].osTimerType, NULL, NULL);
	assert (osTimerList[TMR_IDX_SMB_DATA_SHOW].osTimerId != NULL);
	strcpy (osTimerList[TMR_IDX_SMB_DATA_SHOW].timer_description, "TMR_IDX_SMB_DATA_SHOW");

	osTimerList[TMR_IDX_SMB_STATUS_REPORT].osTimerType = osTimerPeriodic;
	osTimerList[TMR_IDX_SMB_STATUS_REPORT].timeout_tick = SMB_STATUS_REPORT_TIMEOUT;
	osTimerList[TMR_IDX_SMB_STATUS_REPORT].timeout_cb = smb_status_report_cb;
	osTimerList[TMR_IDX_SMB_STATUS_REPORT].osTimerId = osTimerNew(osTimerList[TMR_IDX_SMB_STATUS_REPORT].timeout_cb, osTimerList[TMR_IDX_SMB_STATUS_REPORT].osTimerType, NULL, NULL);
	assert (osTimerList[TMR_IDX_SMB_STATUS_REPORT].osTimerId != NULL);
	strcpy (osTimerList[TMR_IDX_SMB_STATUS_REPORT].timer_description, "TMR_IDX_SMB_STATUS_REPORT");

	osTimerList[TMR_IDX_SMB_IAP_REQUEST].osTimerType = osTimerPeriodic;
	osTimerList[TMR_IDX_SMB_IAP_REQUEST].timeout_tick = SOH_REQ_TIMEOUT;
	osTimerList[TMR_IDX_SMB_IAP_REQUEST].timeout_cb = SOH_req_timeout_cb;
	osTimerList[TMR_IDX_SMB_IAP_REQUEST].osTimerId = osTimerNew(osTimerList[TMR_IDX_SMB_IAP_REQUEST].timeout_cb, osTimerList[TMR_IDX_SMB_IAP_REQUEST].osTimerType, NULL, NULL);
	assert (osTimerList[TMR_IDX_SMB_IAP_REQUEST].osTimerId != NULL);
	strcpy (osTimerList[TMR_IDX_SMB_IAP_REQUEST].timer_description, "TMR_IDX_SMB_IAP_REQUEST");

	osTimerList[TMR_IDX_SMB_MANIPULATION].osTimerType = osTimerOnce;
	osTimerList[TMR_IDX_SMB_MANIPULATION].timeout_tick = SMB_MANIPULATION_TIMEOUT;
	osTimerList[TMR_IDX_SMB_MANIPULATION].timeout_cb = SMB_manipulation_timeout_cb;
	osTimerList[TMR_IDX_SMB_MANIPULATION].osTimerId = osTimerNew(osTimerList[TMR_IDX_SMB_MANIPULATION].timeout_cb, osTimerList[TMR_IDX_SMB_MANIPULATION].osTimerType, NULL, NULL);
	assert (osTimerList[TMR_IDX_SMB_MANIPULATION].osTimerId != NULL);
	strcpy (osTimerList[TMR_IDX_SMB_MANIPULATION].timer_description, "TMR_IDX_SMB_MANIPULATION");

	assert (led_act_toggle_begin() == true);
	assert (uptime_counter_begin() == true);

	return true;
}
