/**
 ******************************************************************************
  * File Name          : func_adc.c
  * Description        : This file is generated by 위대한 송 인재 on Aug 29, 2025
 ******************************************************************************
 *
 * COPYRIGHT(c) 2024 DSN Co. Ltd.
 *
 * Redistribution and use in source and binary forms, with or without modification,
 * are permitted provided that the following conditions are met:
 *   1. Redistributions of source code must retain the above copyright notice,
 *      this list of conditions and the following disclaimer.
 *   2. Redistributions in binary form must reproduce the above copyright notice,
 *      this list of conditions and the following disclaimer in the documentation
 *      and/or other materials provided with the distribution.
 *   3. Neither the name of STMicroelectronics nor the names of its contributors
 *      may be used to endorse or promote products derived from this software
 *      without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 ******************************************************************************
 */

#include "main.h"


/* ADC handler declaration */
/* Variables for ADC conversion data */
__IO   uint16_t   aADCxConvertedData[ADC_CONVERTED_DATA_BUFFER_SIZE]; /* ADC group regular conversion data (array of data) */
SMB_adc_value_t SMB_adc_value;

bool adc_read_begin (void)
{
	assert (osTimerList[TMR_IDX_ADC_READ].osTimerId != NULL);
	assert (osTimerStart(osTimerList[TMR_IDX_ADC_READ].osTimerId, SMB_ADC_READ_TIMEOUT) == osOK);
	return true;
}

bool adc_do_calibration(void)
{
	uint32_t i = 0;

	for (i = 0; i < ADC_CONVERTED_DATA_BUFFER_SIZE; i++) {
		aADCxConvertedData[i] = VAR_CONVERTED_DATA_INIT_VALUE;
	}

	assert (HAL_ADCEx_Calibration_Start(&hadc1, ADC_SINGLE_ENDED) == HAL_OK);

	return true;
}

#define AED_TEMP_TABLE_SIZE		80U
#define AED_TEMP_TABLE_1ST		(0U)
#define AED_TEMP_TABLE_LAST		(AED_TEMP_TABLE_SIZE-1)

typedef struct {
	int16_t converted_temperature;
	uint16_t aed_adc_value;
} aed_adc_temp_t;

static const aed_adc_temp_t aed_temperature_table[AED_TEMP_TABLE_SIZE] = {
		{-20,	3852},
		{-19,	3733},
		{-18,	3615},
		{-17,	3499},
		{-16,	3384},
		{-15,	3270},
		{-14,	3159},
		{-13,	3049},
		{-12,	2941},
		{-11,	2835},
		{-10,	2731},
		{-9,	2629},
		{-8,	2530},
		{-7,	2433},
		{-6,	2339},
		{-5,	2247},
		{-4,	2157},
		{-3,	2070},
		{-2,	1986},
		{-1,	1904},
		{0,		1825},
		{1,		1748},
		{2,		1674},
		{3,		1602},
		{4,		1533},
		{5,		1465},
		{6,		1401},
		{7,		1338},
		{8,		1278},
		{9,		1219},
		{10,	1163},
		{11,	1110},
		{12,	1058},
		{13,	1008},
		{14,	960},
		{15,	914},
		{16,	870},
		{17,	828},
		{18,	788},
		{19,	749},
		{20,	712},
		{21,	676},
		{22,	642},
		{23,	609},
		{24,	578},
		{25,	547},
		{26,	518},
		{27,	490},
		{28,	463},
		{29,	438},
		{30,	413},
		{31,	389},
		{32,	367},
		{33,	345},
		{34,	324},
		{35,	304},
		{36,	285},
		{37,	266},
		{38,	249},
		{39,	232},
		{40,	216},
		{41,	200},
		{42,	185},
		{43,	171},
		{44,	157},
		{45,	144},
		{46,	131},
		{47,	119},
		{48,	107},
		{49,	96},
		{50,	86},
		{51,	75},
		{52,	66},
		{53,	56},
		{54,	47},
		{55,	38},
		{56,	30},
		{57,	22},
		{58,	14},
		{59,	7},
};

int16_t __LL_ADC_CALC_DATA_TO_TEMP(uint16_t aedt_adc_value)
{
	for (uint32_t i = 0 ; i < AED_TEMP_TABLE_SIZE ; i++) {
		if (aedt_adc_value >= aed_temperature_table[i].aed_adc_value) return (aed_temperature_table[i].converted_temperature);
		else continue;
	}

	return aed_temperature_table[AED_TEMP_TABLE_LAST].converted_temperature;
}
