/**
 ******************************************************************************
 * File Name          : sb_thread_iap.c
 * Description        : This file is generated by 위대한 송 인재 on Mar 25, 2025
 ******************************************************************************
 *
 * COPYRIGHT(c) 2024 DSN Co. Ltd.
 *
 * Redistribution and use in source and binary forms, with or without modification,
 * are permitted provided that the following conditions are met:
 *   1. Redistributions of source code must retain the above copyright notice,
 *      this list of conditions and the following disclaimer.
 *   2. Redistributions in binary form must reproduce the above copyright notice,
 *      this list of conditions and the following disclaimer in the documentation
 *      and/or other materials provided with the distribution.
 *   3. Neither the name of STMicroelectronics nor the names of its contributors
 *      may be used to endorse or promote products derived from this software
 *      without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 ******************************************************************************
 */

#include "main.h"

#define IAP_MSG_Q_DEPTH			8
osMessageQueueId_t				iapThreadQ;

iap_msg_func					iap_msg_handler[IAP_MSG_END];
iap_se_func						iap_se_machine[IAP_STATE_END][YPKT_EVENT_END];

iapObj_t 		iapObj;

bool iap_msg_handler_init(iap_msg_func *);
osMemoryPoolId_t iap_mpool_open (uint32_t block_count, uint32_t block_size);
bool iap_se_machine_init();
bool iap_channel_open (UART_HandleTypeDef *huart);
bool iapObj_init(iapObj_t *iapObjp);

bool SOH_req_begin ()
{
	assert (osTimerList[TMR_IDX_SMB_IAP_REQUEST].osTimerId != NULL);
	assert (osTimerStart(osTimerList[TMR_IDX_SMB_IAP_REQUEST].osTimerId, SOH_REQ_TIMEOUT) == osOK);
	return true;
}

void smb_thread_iap (void *arg)
{
	iap_msg_t iap_msg;

	assert (iapObj_init(&iapObj) == true);
	assert (iap_msg_handler_init(iap_msg_handler) == true);
	assert (iap_se_machine_init() == true);
	assert (iap_channel_open(&huart4) == true);
	assert (SOH_req_begin() == true);

	iapThreadQ = osMessageQueueNew(IAP_MSG_Q_DEPTH, sizeof(rb_msg_t), NULL);
	while (1) {
		memset (&iap_msg, 0, sizeof(iap_msg));
		assert (osMessageQueueGet(iapThreadQ, &iap_msg, NULL, osWaitForever) == osOK);
		assert (iap_msg.head.dst == WORKM_IAP);
		assert (iap_msg.head.src == WORKM_UART4);
		assert (iap_msg_handler[iap_msg.head.type](&iap_msg) == true);
		(iap_msg.body.mpool != NULL)?free(iap_msg.body.mpool):(void)0;
	}
}
