/**
 ******************************************************************************
  * File Name          : smb_thread_man.c
  * Description        : This file is generated by 위대한 송 인재 on Aug 29, 2025
 ******************************************************************************
 *
 * COPYRIGHT(c) 2024 DSN Co. Ltd.
 *
 * Redistribution and use in source and binary forms, with or without modification,
 * are permitted provided that the following conditions are met:
 *   1. Redistributions of source code must retain the above copyright notice,
 *      this list of conditions and the following disclaimer.
 *   2. Redistributions in binary form must reproduce the above copyright notice,
 *      this list of conditions and the following disclaimer in the documentation
 *      and/or other materials provided with the distribution.
 *   3. Neither the name of STMicroelectronics nor the names of its contributors
 *      may be used to endorse or promote products derived from this software
 *      without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 ******************************************************************************
 */

#include "main.h"

#define MAN_MSG_Q_DEPTH		8

bool manager_msg_handler_tbl_init(void);
bool adc_read_begin (void);
bool adc_do_calibration(void);
bool ims_sensor_channel_open(void);
bool data_show_begin (void);
bool peri_oper_begin();

uint8_t 				ims_rx_buffer[IMS_RX_BUF_SIZE];
manager_msg_func		manager_msg_handler_tbl[MANAGER_MSG_END];
osMessageQueueId_t		managerThreadQ;

static bool smb_peripheral_outpout_set(SMB_ControlObj_t *pControlObj)
{
	pControlObj->ledbarObj.ledbar_color_set(LEDBAR_OFF);
	pControlObj->sirenObj.siren_set(SIREN_OFF);
	pControlObj->lteObj.lte_set(LTE_ON);
	pControlObj->ptcObj.ptc_set(PTC_OFF);
	pControlObj->yucharObj.yuchar_set(YUCHAR_ON);
	pControlObj->muchar1Obj.muchar1_set(MUCHAR1_ON);
	pControlObj->muchar2Obj.muchar2_set(MUCHAR2_ON);
	pControlObj->fanObj.fan_set(FAN_OFF);
	pControlObj->inverterObj.inverter_set(INVERTER_OFF);
	pControlObj->speakerObj.speaker_set(SPEAKER_OFF);
	pControlObj->lcdObj.lcd_set(LCD_ON);
	pControlObj->lampObj.lamp_set(LAMP_OFF);

	aclamp0_off;
	aclamp1_off;
	aclamp2_off;

	return true;
}

void smb_thread_manager (void *arg)
{
	manager_msg_t manager_msg;

	assert (manager_msg_handler_tbl_init() == true);
	assert (adc_do_calibration() == true);
	// 여기서 한번은 ADC 를 읽어 줘서 AEDT 가 제대로 된 값이 들어 있게 해야만 아래 peri_oper_begin() 으로 500ms 후에 manager_msg_handler_peri_oper() 을 수행할 때 AEDT/FAN 이 제대로 동작하게 할 수 있다.
	// ADC 는 1초 주기, peri 는 500ms 주기로 하기 때문에 peri 제어가 먼저 시작되면서 초기화되지 않은 AEDT 때문에 PTC 를 켜고 나서 제대로 온도가 읽혀도 PTC 가 계속 켜지게 되는 문제를 방지할 수 있다.
	assert (HAL_ADC_Start_DMA(&hadc1, (uint32_t *)aADCxConvertedData, ADC_CONVERTED_DATA_BUFFER_SIZE) == HAL_OK);

	assert (ims_sensor_channel_open() == true);
	assert (smb_peripheral_outpout_set(&SMB_ControlObj) == true);
	assert (peri_oper_begin() == true);
	assert (adc_read_begin() == true);
	assert (data_show_begin() == true);

	managerThreadQ = osMessageQueueNew(MAN_MSG_Q_DEPTH, sizeof(manager_msg), NULL);
	while (1) {
		memset (&manager_msg, 0, sizeof(manager_msg));
		assert (osMessageQueueGet(managerThreadQ, &manager_msg, NULL, osWaitForever) == osOK);
		assert (manager_msg.head.type < MANAGER_MSG_END);
		assert (manager_msg.head.dst == WORKM_MANAGER);
		assert (manager_msg_handler_tbl[manager_msg.head.type](&manager_msg) == true);
	}
}
