/**
 ******************************************************************************
  * File Name          : smb_thread_cli.c
  * Description        : This file is generated by 위대한 송 인재 on Aug 22, 2025
 ******************************************************************************
 *
 * COPYRIGHT(c) 2024 DSN Co. Ltd.
 *
 * Redistribution and use in source and binary forms, with or without modification,
 * are permitted provided that the following conditions are met:
 *   1. Redistributions of source code must retain the above copyright notice,
 *      this list of conditions and the following disclaimer.
 *   2. Redistributions in binary form must reproduce the above copyright notice,
 *      this list of conditions and the following disclaimer in the documentation
 *      and/or other materials provided with the distribution.
 *   3. Neither the name of STMicroelectronics nor the names of its contributors
 *      may be used to endorse or promote products derived from this software
 *      without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 ******************************************************************************
 */

#include "main.h"


bool smb_cmd_bench_add ();
bool smb_cmd_system_add ();
bool smb_cmd_eflash_add ();
bool smb_cmd_fs_add ();
bool smb_cmd_misc_add ();
bool smb_cmd_rb_add ();
bool smb_cmd_misc_add ();

void RunCmdTask(SYS_CMD_IO_DCPT* pCmdIO);
bool uartObj_Init( void );
bool SYS_CMD_Initialize(const SYS_MODULE_INIT * const init );
SYS_MODULE_OBJ SYS_CONSOLE_Initialize (const SYS_MODULE_INDEX index, const SYS_MODULE_INIT* const init);
SYS_CMD_DEVICE_NODE* SYS_CMDIO_ADD(const SYS_CMD_API* opApi, const void* cmdIoParam, int unused);
bool RxPushByte (uint8_t rdByte);
void Greeting(void);

extern const SYS_CMD_INIT sysCmdInit;
extern const SYS_CONSOLE_INIT sysConsole0Init;
extern const SYS_CMD_API sysConsoleApi;
extern SYS_CMD_INIT _cmdInitData;
extern SYS_CMD_DEVICE_LIST	cmdIODevList;

static	uint8_t				ConsoleChar;

void RxCpltCallback(void)
{
	RxPushByte (ConsoleChar);
	HW_UART_Receive_IT(CFG_DEBUG_TRACE_UART, &ConsoleChar, 1U, RxCpltCallback);
}

static bool console_init ()
{
	assert (uartObj_Init() == true);
	assert (SYS_CMD_Initialize((SYS_MODULE_INIT*)&sysCmdInit) == true);
	assert (SYS_CONSOLE_Initialize(SYS_CONSOLE_INDEX_0, (SYS_MODULE_INIT *)&sysConsole0Init) != SYS_MODULE_OBJ_INVALID);
	assert (SYS_CMDIO_ADD(&sysConsoleApi, &_cmdInitData.consoleCmdIOParam, _cmdInitData.consoleCmdIOParam) != 0);

	return true;
}

static bool solbench_cmds_add ()
{
	assert (smb_cmd_system_add () == true);
	assert (smb_cmd_fs_add () == true);
	assert (smb_cmd_bench_add () == true);
	assert (smb_cmd_misc_add () == true);
//	assert (smb_cmd_rb_add () == true);

	return true;
}

static bool console_scan_begin ()
{
	assert (osTimerList[TMR_IDX_CLI_CONSOLE_SCAN].osTimerId != NULL);
	assert (osTimerStart(osTimerList[TMR_IDX_CLI_CONSOLE_SCAN].osTimerId, CONSOLE_SCAN_TIMEOUT) == osOK);
	return true;
}

void smb_thread_cli (void *arg)
{
	uint32_t cli_event_flag = 0;
	uint32_t cli_wait_flag = 		\
			EF_CONSOLE_SCAN			\
			;

	assert (console_init () == true);
	assert (solbench_cmds_add () == true);
	HW_UART_Receive_IT(CFG_DEBUG_TRACE_UART, &ConsoleChar, 1U, RxCpltCallback);
	HAL_NVIC_EnableIRQ(USART1_IRQn);
	Greeting();
	assert (console_scan_begin () == true);
	while (1) {
		cli_event_flag = osThreadFlagsWait(cli_wait_flag, osFlagsWaitAny, osWaitForever);
		assert (!(cli_event_flag & THREAD_FLAG_MASK_ERROR));

		if (cli_event_flag & EF_CONSOLE_SCAN) {
			RunCmdTask(cmdIODevList.head);
		}
	}
}
