/**
 ******************************************************************************
  * File Name          : smb_thread_rb.c
  * Description        : This file is generated by 위대한 송 인재 on Sep 2, 2025
 ******************************************************************************
 *
 * COPYRIGHT(c) 2024 DSN Co. Ltd.
 *
 * Redistribution and use in source and binary forms, with or without modification,
 * are permitted provided that the following conditions are met:
 *   1. Redistributions of source code must retain the above copyright notice,
 *      this list of conditions and the following disclaimer.
 *   2. Redistributions in binary form must reproduce the above copyright notice,
 *      this list of conditions and the following disclaimer in the documentation
 *      and/or other materials provided with the distribution.
 *   3. Neither the name of STMicroelectronics nor the names of its contributors
 *      may be used to endorse or promote products derived from this software
 *      without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 ******************************************************************************
 */

#include "main.h"

#define RB_MSG_Q_DEPTH			8
#define	RB_REG_REPORT_TIMEOUT	TIMEOUT_1_SEC
rb_msg_func						rb_msg_handler_tbl[RB_MSG_END];
osMessageQueueId_t				rbThreadQ;
uint8_t 						Rb_Rx_Buf[RB_MSG_SIZE];

bool rb_channel_open (UART_HandleTypeDef *);
bool rb_msg_handler_tbl_init ();
bool RbSendQueueBuffInit(void);

static bool rb_status_report_begin ()
{
	assert (osTimerList[TMR_IDX_SMB_STATUS_REPORT].osTimerId != NULL);
	assert (osTimerStart(osTimerList[TMR_IDX_SMB_STATUS_REPORT].osTimerId, SMB_STATUS_REPORT_TIMEOUT) == osOK);
	return true;
}

void smb_thread_rb (void *arg)
{
	rb_msg_t rb_msg;

	assert (rb_msg_handler_tbl_init() == true);
	assert (rb_channel_open(&RbUartHandle) == true);
	assert (RbSendQueueBuffInit() == true);
	assert (rb_status_report_begin() == true);
	rbThreadQ = osMessageQueueNew(RB_MSG_Q_DEPTH, sizeof(rb_msg_t), NULL);
	while (1) {
		memset (&rb_msg, 0, sizeof(rb_msg));
		assert (osMessageQueueGet(rbThreadQ, &rb_msg, NULL, osWaitForever) == osOK);
		assert (rb_msg.head.type < RB_MSG_END);
		assert (rb_msg.head.dst == WORKM_RB);
		assert (rb_msg.head.len == RBERRY_MSG_LENGTH);

		assert (rb_msg_handler_tbl[rb_msg.head.type](&rb_msg) == true);
	}
}
