/**
 ******************************************************************************
  * File Name          : app_entry.c
  * Description        : This file is generated by 위대한 송 인재 on Feb 26, 2025
 ******************************************************************************
 *
 * COPYRIGHT(c) 2024 DSN Co. Ltd.
 *
 * Redistribution and use in source and binary forms, with or without modification,
 * are permitted provided that the following conditions are met:
 *   1. Redistributions of source code must retain the above copyright notice,
 *      this list of conditions and the following disclaimer.
 *   2. Redistributions in binary form must reproduce the above copyright notice,
 *      this list of conditions and the following disclaimer in the documentation
 *      and/or other materials provided with the distribution.
 *   3. Neither the name of STMicroelectronics nor the names of its contributors
 *      may be used to endorse or promote products derived from this software
 *      without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 ******************************************************************************
 */

#include "main.h"


osThreadId_t Thread_INIT_Handler;
osThreadId_t Thread_CLI_Handler;
osThreadId_t Thread_IAP_Handler;
osThreadId_t Thread_SENSOR_Handler;
osThreadId_t Thread_ADC_Handler;

void smb_thread_init (void *arg);
void smb_thread_cli (void *arg);
void solbench_thread_rb (void *arg);
void solbench_thread_sensor (void *arg);
void solbench_thread_adc (void *arg);

/******************************************************************************
 * Thread Initial attributes
 ******************************************************************************/
#define CFG_INIT_THREAD_NAME        "THREAD_INIT"
#define CFG_INIT_THREAD_ATTR_BITS   (0)
#define CFG_INIT_THREAD_CB_MEM      (0)
#define CFG_INIT_THREAD_CB_SIZE     (0)
#define CFG_INIT_THREAD_STACK_MEM   (0)
#define CFG_INIT_THREAD_PRIORITY    osPriorityHigh
#define CFG_INIT_THREAD_STACK_SIZE  (configMINIMAL_STACK_SIZE * 32)

const osThreadAttr_t SMB_INIT_Thread_attr = {
		.name = 		CFG_INIT_THREAD_NAME,
		.attr_bits = 	CFG_INIT_THREAD_ATTR_BITS,
		.cb_mem = 		CFG_INIT_THREAD_CB_MEM,
		.cb_size = 		CFG_INIT_THREAD_CB_SIZE,
		.stack_mem = 	CFG_INIT_THREAD_STACK_MEM,
		.priority = 	CFG_INIT_THREAD_PRIORITY,
		.stack_size = 	CFG_INIT_THREAD_STACK_SIZE
};

/******************************************************************************
 * Thread CLI attributes
 ******************************************************************************/
#define CFG_CLI_PROCESS_NAME        "THREAD_CLI"
#define CFG_CLI_PROCESS_ATTR_BITS   (0)
#define CFG_CLI_PROCESS_CB_MEM      (0)
#define CFG_CLI_PROCESS_CB_SIZE     (0)
#define CFG_CLI_PROCESS_STACK_MEM   (0)
#define CFG_CLI_PROCESS_PRIORITY    osPriorityNormal
#define CFG_CLI_PROCESS_STACK_SIZE  (configMINIMAL_STACK_SIZE * 32)		// 32 로 한다. 16 으로 하면 fsmkdir 같은 명령어를 수행한 다음에 console 이 서버리는 것 같은 문제가 발생한다.

const osThreadAttr_t SMB_Cli_Thread_attr = {
		.name = 		CFG_CLI_PROCESS_NAME,
		.attr_bits = 	CFG_CLI_PROCESS_ATTR_BITS,
		.cb_mem = 		CFG_CLI_PROCESS_CB_MEM,
		.cb_size = 		CFG_CLI_PROCESS_CB_SIZE,
		.stack_mem = 	CFG_CLI_PROCESS_STACK_MEM,
		.priority = 	CFG_CLI_PROCESS_PRIORITY,
		.stack_size = 	CFG_CLI_PROCESS_STACK_SIZE
};

/******************************************************************************
 * Thread RB attributes
 ******************************************************************************/
#define CFG_RB_THREAD_NAME        "THREAD_RB"
#define CFG_RB_THREAD_ATTR_BITS   (0)
#define CFG_RB_THREAD_CB_MEM      (0)
#define CFG_RB_THREAD_CB_SIZE     (0)
#define CFG_RB_THREAD_STACK_MEM   (0)
#define CFG_RB_THREAD_PRIORITY    osPriorityAboveNormal
#define CFG_RB_THREAD_STACK_SIZE  (configMINIMAL_STACK_SIZE * 8)

const osThreadAttr_t SolBench_RB_Thread_Attr = {
		.name = 		CFG_RB_THREAD_NAME,
		.attr_bits = 	CFG_RB_THREAD_ATTR_BITS,
		.cb_mem = 		CFG_RB_THREAD_CB_MEM,
		.cb_size = 		CFG_RB_THREAD_CB_SIZE,
		.stack_mem = 	CFG_RB_THREAD_STACK_MEM,
		.stack_size = 	CFG_RB_THREAD_STACK_SIZE,
		.priority = 	CFG_RB_THREAD_PRIORITY
};


/******************************************************************************
 * Thread SENSOR attributes
 ******************************************************************************/
#define CFG_SENSOR_THREAD_NAME        "THREAD_SENSOR"
#define CFG_SENSOR_THREAD_ATTR_BITS   (0)
#define CFG_SENSOR_THREAD_CB_MEM      (0)
#define CFG_SENSOR_THREAD_CB_SIZE     (0)
#define CFG_SENSOR_THREAD_STACK_MEM   (0)
#define CFG_SENSOR_THREAD_PRIORITY    osPriorityBelowNormal
#define CFG_SENSOR_THREAD_STACK_SIZE  (configMINIMAL_STACK_SIZE * 8)

const osThreadAttr_t SolBench_SENSOR_Thread_Attr = {
		.name = 		CFG_SENSOR_THREAD_NAME,
		.attr_bits = 	CFG_SENSOR_THREAD_ATTR_BITS,
		.cb_mem = 		CFG_SENSOR_THREAD_CB_MEM,
		.cb_size = 		CFG_SENSOR_THREAD_CB_SIZE,
		.stack_mem = 	CFG_SENSOR_THREAD_STACK_MEM,
		.stack_size = 	CFG_SENSOR_THREAD_STACK_SIZE,
		.priority = 	CFG_SENSOR_THREAD_PRIORITY
};

/******************************************************************************
 * Thread ADC attributes
 ******************************************************************************/
#define CFG_ADC_THREAD_NAME        "THREAD_ADC"
#define CFG_ADC_THREAD_ATTR_BITS   (0)
#define CFG_ADC_THREAD_CB_MEM      (0)
#define CFG_ADC_THREAD_CB_SIZE     (0)
#define CFG_ADC_THREAD_STACK_MEM   (0)
#define CFG_ADC_THREAD_PRIORITY    osPriorityLow
#define CFG_ADC_THREAD_STACK_SIZE  (configMINIMAL_STACK_SIZE * 8)

const osThreadAttr_t SolBench_ADC_Thread_Attr = {
		.name = 		CFG_ADC_THREAD_NAME,
		.attr_bits = 	CFG_ADC_THREAD_ATTR_BITS,
		.cb_mem = 		CFG_ADC_THREAD_CB_MEM,
		.cb_size = 		CFG_ADC_THREAD_CB_SIZE,
		.stack_mem = 	CFG_ADC_THREAD_STACK_MEM,
		.stack_size = 	CFG_ADC_THREAD_STACK_SIZE,
		.priority = 	CFG_ADC_THREAD_PRIORITY
};

bool app_entry ()
{
	Thread_INIT_Handler = osThreadNew(smb_thread_init, NULL, &SMB_INIT_Thread_attr);
	assert (Thread_INIT_Handler != NULL);

	Thread_CLI_Handler = osThreadNew(smb_thread_cli, NULL, &SMB_Cli_Thread_attr);
	assert (Thread_CLI_Handler != NULL);

//	Thread_IAP_Handler = osThreadNew(solbench_thread_rb, NULL, &SolBench_RB_Thread_Attr);
//	assert (Thread_IAP_Handler != NULL);
//
//	Thread_SENSOR_Handler = osThreadNew(solbench_thread_rb, NULL, &SolBench_SENSOR_Thread_Attr);
//	assert (Thread_SENSOR_Handler != NULL);
//
//	Thread_ADC_Handler = osThreadNew(solbench_thread_adc, NULL, &SolBench_ADC_Thread_Attr);
//	assert (Thread_ADC_Handler != NULL);

	return true;
}
