/**
 ******************************************************************************
  * File Name          : head_thread.h
  * Description        : This file is generated by 위대한 송 인재 on Feb 26, 2025
 ******************************************************************************
 *
 * COPYRIGHT(c) 2024 DSN Co. Ltd.
 *
 * Redistribution and use in source and binary forms, with or without modification,
 * are permitted provided that the following conditions are met:
 *   1. Redistributions of source code must retain the above copyright notice,
 *      this list of conditions and the following disclaimer.
 *   2. Redistributions in binary form must reproduce the above copyright notice,
 *      this list of conditions and the following disclaimer in the documentation
 *      and/or other materials provided with the distribution.
 *   3. Neither the name of STMicroelectronics nor the names of its contributors
 *      may be used to endorse or promote products derived from this software
 *      without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 ******************************************************************************
 */


#ifndef INC_HEAD_HEAD_THREAD_H_
#define INC_HEAD_HEAD_THREAD_H_

#define	THREAD_FLAG_MASK_ERROR					0x80000000U

// *****************************************************************************
// Thread Flag Mask definition for ROOT thread
// *****************************************************************************
typedef enum {
	TFM_ROOT_ROUTINE_JOB = 0,
	TFM_ROOT_RSVD_1,
	TFM_ROOT_RSVD_2,
	TFM_ROOT_RSVD_3,
	TFM_ROOT_RSVD_4,
	TFM_ROOT_RSVD_5,
	TFM_ROOT_RSVD_6,
	TFM_ROOT_RSVD_7,
	TFM_ROOT_RSVD_8,
	TFM_ROOT_RSVD_9,
	TFM_ROOT_RSVD_10,
	TFM_ROOT_RSVD_11,
	TFM_ROOT_RSVD_12,
	TFM_ROOT_RSVD_13,
	TFM_ROOT_RSVD_14,
	TFM_ROOT_RSVD_15,
	TFM_ROOT_RSVD_16,
	TFM_ROOT_RSVD_17,
	TFM_ROOT_RSVD_18,
	TFM_ROOT_RSVD_19,
	TFM_ROOT_RSVD_20,
	TFM_ROOT_RSVD_21,
	TFM_ROOT_RSVD_22,
	TFM_ROOT_RSVD_23,
	TFM_ROOT_RSVD_24,
	TFM_ROOT_RSVD_25,
	TFM_ROOT_RSVD_26,
	TFM_ROOT_RSVD_27,
	TFM_ROOT_RSVD_28,
	TFM_ROOT_RSVD_29,
	TFM_ROOT_RSVD_30,
	TFM_ROOT_MAX_VALUE = 31,
} Thread_Flag_Mask_ROOT_t;

#define	EVT_FLAG_ROOT_ROUTINE_JOB			(1 << TFM_ROOT_ROUTINE_JOB)


// *****************************************************************************
// Thread Flag Mask definition for CLI thread
// *****************************************************************************
typedef enum {
	TFM_CLI_CONSOLE_SCAN = 0,
	TFM_CLI_RSVD_1,
	TFM_CLI_RSVD_2,
	TFM_CLI_RSVD_3,
	TFM_CLI_RSVD_4,
	TFM_CLI_RSVD_5,
	TFM_CLI_RSVD_6,
	TFM_CLI_RSVD_7,
	TFM_CLI_RSVD_8,
	TFM_CLI_RSVD_9,
	TFM_CLI_RSVD_10,
	TFM_CLI_RSVD_11,
	TFM_CLI_RSVD_12,
	TFM_CLI_RSVD_13,
	TFM_CLI_RSVD_14,
	TFM_CLI_RSVD_15,
	TFM_CLI_RSVD_16,
	TFM_CLI_RSVD_17,
	TFM_CLI_RSVD_18,
	TFM_CLI_RSVD_19,
	TFM_CLI_RSVD_20,
	TFM_CLI_RSVD_21,
	TFM_CLI_RSVD_22,
	TFM_CLI_RSVD_23,
	TFM_CLI_RSVD_24,
	TFM_CLI_RSVD_25,
	TFM_CLI_RSVD_26,
	TFM_CLI_RSVD_27,
	TFM_CLI_RSVD_28,
	TFM_CLI_RSVD_29,
	TFM_CLI_RSVD_30,
	TFM_CLI_MAX_VALUE = 31,
} Thread_Flag_Mask_CLI_t;

#define	EF_CONSOLE_SCAN					(1 << TFM_CLI_CONSOLE_SCAN)



#endif /* INC_HEAD_HEAD_THREAD_H_ */
