/**
 ******************************************************************************
  * File Name          : head_typedef.h
  * Description        : This file is generated by 위대한 송 인재 on Jul 30, 2025
 ******************************************************************************
 *
 * COPYRIGHT(c) 2024 DSN Co. Ltd.
 *
 * Redistribution and use in source and binary forms, with or without modification,
 * are permitted provided that the following conditions are met:
 *   1. Redistributions of source code must retain the above copyright notice,
 *      this list of conditions and the following disclaimer.
 *   2. Redistributions in binary form must reproduce the above copyright notice,
 *      this list of conditions and the following disclaimer in the documentation
 *      and/or other materials provided with the distribution.
 *   3. Neither the name of STMicroelectronics nor the names of its contributors
 *      may be used to endorse or promote products derived from this software
 *      without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 ******************************************************************************
 */


#ifndef INC_HEAD_TYPEDEF_H_
#define INC_HEAD_TYPEDEF_H_

typedef struct {
	uint32_t 			machine_serial_no;
	uint32_t			hw_version;
	smb_work_mode_t		work_mode;
	smb_banner_t		banner;				// booting 할 때 console 에 표시되는 그림 선택
	char				site_address[SMB_CONFIG_STRING_SIZE_MAX];
	char				install_worker[SMB_CONFIG_STRING_SIZE_MAX];
	RTC_DateTypeDef 	install_Date;
	RTC_DateTypeDef 	manufacture_Date;
	RTC_DateTypeDef 	fw_update_Date;
	char				running_fw[SMB_CONFIG_STRING_SIZE_MAX];
} SMB_ConfigObj_t;

typedef struct {
	char				fw_version[64];
	RTC_DateTypeDef 	launchDate;
	RTC_TimeTypeDef 	launchTime;
	RTC_DateTypeDef 	currentDate;
	RTC_TimeTypeDef 	currentTime;
	uint64_t			uptime_counter;
} SMB_StatusObj_t;


/*******************************************************************************************
 * osTimer
 ******************************************************************************************/
#define OS_TIMER_DESC_STR_LENGTH	50
typedef void (* func_timeout_cb)(void *);

typedef struct {
	osTimerId_t			osTimerId;
	osTimerType_t		osTimerType;
	uint32_t			timeout_tick;
	func_timeout_cb		timeout_cb;
	char				timer_description[OS_TIMER_DESC_STR_LENGTH];
} osTimerEntry_t;

typedef enum {
	TMR_IDX_BEGIN = 0,
	TMR_IDX_LED_ACT_TOGGLE = TMR_IDX_BEGIN,
	TMR_IDX_CLI_CONSOLE_SCAN,
	TMR_IDX_UPTIME_COUNT,
	TMR_IDX_END,
} osTimerIndex_t;

/*******************************************************************************************
 * Interrupt counter
 ******************************************************************************************/
typedef struct {
	uint32_t 		RCC_Intr_count;
	uint32_t 		DMA1_Chan_1_count;
	uint32_t 		DMA1_Chan_3_count;
	uint32_t 		DMA1_Chan_4_count;
	uint32_t 		DMA1_Chan_6_count;
	uint32_t 		DMA1_Chan_7_count;
	uint32_t 		ADC1_2_count;
	uint32_t 		EXTI9_5_count;
	uint32_t 		TIM1_UP_16_count;
	uint32_t 		TIM4_count;
	uint32_t 		SPI1_count;
	uint32_t 		USART1_count;
	uint32_t 		USART2_count;
	uint32_t 		USART3_count;
	uint32_t 		EXTI15_10_count;
	uint32_t 		USART4_count;
	uint32_t 		DMA2_Chan_3_count;		// IAP Tx
	uint32_t 		DMA2_Chan_5_count;		// IAP Rx
} SMBIntrObj_t;








#endif /* INC_HEAD_TYPEDEF_H_ */
