/**
 ******************************************************************************
  * File Name          : head_enum.h
  * Description        : This file is generated by 위대한 송 인재 on Jul 30, 2025
 ******************************************************************************
 *
 * COPYRIGHT(c) 2024 DSN Co. Ltd.
 *
 * Redistribution and use in source and binary forms, with or without modification,
 * are permitted provided that the following conditions are met:
 *   1. Redistributions of source code must retain the above copyright notice,
 *      this list of conditions and the following disclaimer.
 *   2. Redistributions in binary form must reproduce the above copyright notice,
 *      this list of conditions and the following disclaimer in the documentation
 *      and/or other materials provided with the distribution.
 *   3. Neither the name of STMicroelectronics nor the names of its contributors
 *      may be used to endorse or promote products derived from this software
 *      without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 ******************************************************************************
 */


#ifndef INC_HEAD_HEAD_ENUM_H_
#define INC_HEAD_HEAD_ENUM_H_

typedef enum {
	SMB_MODE_NETWORK = true,
	SMB_MODE_STANDALONE = !SMB_MODE_NETWORK,
} smb_work_mode_t;


typedef enum {
	BANNER_DSN = 0,
	BANNER_SMART,
	BANNER_BENCH,
	BANNER_PEE,
	BANNER_SHIT,
	BANNER_BALLET,
	BANNER_END,
} smb_banner_t;

typedef enum {
	LED_ACT_TOGGLE_TIMEOUT		= TIMEOUT_500_MSEC,
	CONSOLE_SCAN_TIMEOUT		= TIMEOUT_10_MSEC,
	UPTIME_COUNT_TIMEOUT		= TIMEOUT_1_SEC,
} os_timer_timeout_t;












#endif /* INC_HEAD_HEAD_ENUM_H_ */
