/**
 ******************************************************************************
  * File Name          : head_def.h
  * Description        : This file is generated by 위대한 송 인재 on Jul 30, 2025
 ******************************************************************************
 *
 * COPYRIGHT(c) 2024 DSN Co. Ltd.
 *
 * Redistribution and use in source and binary forms, with or without modification,
 * are permitted provided that the following conditions are met:
 *   1. Redistributions of source code must retain the above copyright notice,
 *      this list of conditions and the following disclaimer.
 *   2. Redistributions in binary form must reproduce the above copyright notice,
 *      this list of conditions and the following disclaimer in the documentation
 *      and/or other materials provided with the distribution.
 *   3. Neither the name of STMicroelectronics nor the names of its contributors
 *      may be used to endorse or promote products derived from this software
 *      without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 ******************************************************************************
 */


#ifndef INC_HEAD_HEAD_DEF_H_
#define INC_HEAD_HEAD_DEF_H_

/**
 * @brief STM32WL49x AMIGO BSP Driver
 */
#define __STM32WL49x_AMIGO_BSP_VERSION_MAIN   (0x01U) /*!< [31:24] main version */
#define __STM32WL49x_AMIGO_BSP_VERSION_SUB1   (0x00U) /*!< [23:16] sub1 version */
#define __STM32WL49x_AMIGO_BSP_VERSION_SUB2   (0x04U) /*!< [15:8]  sub2 version */
#define __STM32WL49x_AMIGO_BSP_VERSION_RC     (0x00U) /*!< [7:0]  release candidate */
#define __STM32WL49x_AMIGO_BSP_VERSION        ((__STM32WL49x_AMIGO_BSP_VERSION_MAIN << 24)\
		|(__STM32WL49x_AMIGO_BSP_VERSION_SUB1 << 16)\
		|(__STM32WL49x_AMIGO_BSP_VERSION_SUB2 << 8 )\
		|(__STM32WL49x_AMIGO_BSP_VERSION_RC))

/**
 * @brief STM32WL49x AMIGO BSP Driver
 */
#define __LMS_BOARD_VERSION_MAIN   (0x01U) /*!< [31:24] main version */
#define __LMS_BOARD_VERSION_SUB1   (0x00U) /*!< [23:16] sub1 version */
#define __LMS_BOARD_VERSION_SUB2   (0x00U) /*!< [15:8]  sub2 version */
#define __LMS_BOARD_VERSION_RC     (0x01U) /*!< [7:0]  release candidate */
#define __LMS_BOARD_VERSION        ((__LMS_BOARD_VERSION_MAIN << 24)\
		|(__LMS_BOARD_VERSION_SUB1 << 16)\
		|(__LMS_BOARD_VERSION_SUB2 << 8 )\
		|(__LMS_BOARD_VERSION_RC))

// *****************************************************************************
// Timeout value..
// 1ms tick 기준 0xFFFFFFFF (4,294,967,295 를 넘지 않도록 주의한다..
// *****************************************************************************
#define TIMEOUT_1_MSEC					1U
#define TIMEOUT_2_MSEC					2U
#define TIMEOUT_3_MSEC					3U
#define TIMEOUT_4_MSEC					4U
#define TIMEOUT_5_MSEC					5U
#define TIMEOUT_6_MSEC					6U
#define TIMEOUT_7_MSEC					7U
#define TIMEOUT_8_MSEC					8U
#define TIMEOUT_9_MSEC					9U
#define TIMEOUT_10_MSEC					(10*TIMEOUT_1_MSEC)
#define TIMEOUT_20_MSEC					(2*TIMEOUT_10_MSEC)
#define TIMEOUT_30_MSEC					(3*TIMEOUT_10_MSEC)
#define TIMEOUT_40_MSEC					(4*TIMEOUT_10_MSEC)
#define TIMEOUT_50_MSEC					(5*TIMEOUT_10_MSEC)
#define TIMEOUT_60_MSEC					(6*TIMEOUT_10_MSEC)
#define TIMEOUT_70_MSEC					(7*TIMEOUT_10_MSEC)
#define TIMEOUT_80_MSEC					(8*TIMEOUT_10_MSEC)
#define TIMEOUT_90_MSEC					(9*TIMEOUT_10_MSEC)
#define TIMEOUT_100_MSEC				(10*TIMEOUT_10_MSEC)
#define TIMEOUT_200_MSEC				(2*TIMEOUT_100_MSEC)
#define TIMEOUT_300_MSEC				(3*TIMEOUT_100_MSEC)
#define TIMEOUT_400_MSEC				(4*TIMEOUT_100_MSEC)
#define TIMEOUT_500_MSEC				(5*TIMEOUT_100_MSEC)
#define TIMEOUT_600_MSEC				(6*TIMEOUT_100_MSEC)
#define TIMEOUT_700_MSEC				(7*TIMEOUT_100_MSEC)
#define TIMEOUT_800_MSEC				(8*TIMEOUT_100_MSEC)
#define TIMEOUT_900_MSEC				(9*TIMEOUT_100_MSEC)
#define TIMEOUT_1_SEC					(10*TIMEOUT_100_MSEC)
#define TIMEOUT_2_SEC					(2*TIMEOUT_1_SEC)
#define TIMEOUT_3_SEC					(3*TIMEOUT_1_SEC)
#define TIMEOUT_4_SEC					(4*TIMEOUT_1_SEC)
#define TIMEOUT_5_SEC					(5*TIMEOUT_1_SEC)
#define TIMEOUT_6_SEC					(6*TIMEOUT_1_SEC)
#define TIMEOUT_7_SEC					(7*TIMEOUT_1_SEC)
#define TIMEOUT_8_SEC					(8*TIMEOUT_1_SEC)
#define TIMEOUT_9_SEC					(9*TIMEOUT_1_SEC)
#define TIMEOUT_10_SEC					(10*TIMEOUT_1_SEC)

#define TIMEOUT_1_MIN					(60*TIMEOUT_1_SEC)
#define TIMEOUT_2_MIN					(2*TIMEOUT_1_MIN)
#define TIMEOUT_3_MIN					(3*TIMEOUT_1_MIN)
#define TIMEOUT_4_MIN					(4*TIMEOUT_1_MIN)
#define TIMEOUT_5_MIN					(5*TIMEOUT_1_MIN)
#define TIMEOUT_6_MIN					(6*TIMEOUT_1_MIN)
#define TIMEOUT_7_MIN					(7*TIMEOUT_1_MIN)
#define TIMEOUT_8_MIN					(8*TIMEOUT_1_MIN)
#define TIMEOUT_9_MIN					(9*TIMEOUT_1_MIN)
#define TIMEOUT_10_MIN					(10*TIMEOUT_1_MIN)
#define TIMEOUT_11_MIN					(11*TIMEOUT_1_MIN)
#define TIMEOUT_12_MIN					(12*TIMEOUT_1_MIN)
#define TIMEOUT_13_MIN					(13*TIMEOUT_1_MIN)
#define TIMEOUT_14_MIN					(14*TIMEOUT_1_MIN)
#define TIMEOUT_15_MIN					(15*TIMEOUT_1_MIN)
#define TIMEOUT_16_MIN					(16*TIMEOUT_1_MIN)
#define TIMEOUT_17_MIN					(17*TIMEOUT_1_MIN)
#define TIMEOUT_18_MIN					(18*TIMEOUT_1_MIN)
#define TIMEOUT_19_MIN					(19*TIMEOUT_1_MIN)
#define TIMEOUT_20_MIN					(20*TIMEOUT_1_MIN)

// Text attributes
#define TXT_ATTR_OFF                	"\x1b[0m"       //All attributes off(color at startup)
#define TXT_ATTR_BOLD               	"\x1b[1m"       //Bold on(enable foreground intensity)
#define TXT_ATTR_UNDERLINE          	"\x1b[4m"       //Underline on
#define TXT_ATTR_BLINK              	"\x1b[5m"       //Blink on(enable background intensity)
#define TXT_ATTR_BOLD_OFF           	"\x1b[21m"      //Bold off(disable foreground intensity)
#define TXT_ATTR_UNDERLINE_OFF      	"\x1b[24m"      //Underline off
#define TXT_ATTR_BLINK_OFF           	"\x1b[25m"      //Blink off(disable background intensity)

// Foreground colors
#define RTT_COLOR_CODE_BLACK             "\x1b[30m"      //Black
#define RTT_COLOR_CODE_RED               "\x1b[31m"      //Red
#define RTT_COLOR_CODE_GREEN             "\x1b[32m"      //Green
#define RTT_COLOR_CODE_YELLOW            "\x1b[33m"      //Yellow
#define RTT_COLOR_CODE_BLUE              "\x1b[34m"      //Blue
#define RTT_COLOR_CODE_MAGNETA           "\x1b[35m"      //Magenta
#define RTT_COLOR_CODE_CYAN              "\x1b[36m"      //Cyan
#define RTT_COLOR_CODE_WHITE             "\x1b[37m"      //White
#define RTT_COLOR_CODE_DEFAULT           "\x1b[39m"      //Default(foreground color at startup)
#define RTT_COLOR_CODE_LIGHT_GRAY        "\x1b[90m"      //Light Gray
#define RTT_COLOR_CODE_LIGHT_RED         "\x1b[91m"      //Light Red
#define RTT_COLOR_CODE_LIGHT_GREEN       "\x1b[92m"      //Light Green
#define RTT_COLOR_CODE_LIGHT_YELLOW      "\x1b[93m"      //Light Yellow
#define RTT_COLOR_CODE_LIGHT_BLUE        "\x1b[94m"      //Light Blue
#define RTT_COLOR_CODE_LIGHT_MAGNETA     "\x1b[95m"      //Light Magenta
#define RTT_COLOR_CODE_LIGHT_CYAN        "\x1b[96m"      //Light Cyan
#define RTT_COLOR_LIGHT_WHITE       	 "\x1b[97m"      //Light White

// BOLD colors
#define RTT_COLOR_CODE_BOLD_RED			"\x1b[1;31m"
#define RTT_COLOR_CODE_BOLD_GREEN		"\x1b[1;32m"
#define RTT_COLOR_CODE_BOLD_YELLOW		"\x1b[1;33m"
#define RTT_COLOR_CODE_BOLD_BLUE		"\x1b[1;34m"
#define RTT_COLOR_CODE_BOLD_MAGENTA		"\x1b[1;35m"
#define RTT_COLOR_CODE_BOLD_CYAN		"\x1b[1;36m"
#define RTT_COLOR_CODE_BOLD_WHITE		"\x1b[1;37m"

// Background colors
#define BG_COLOR_BLACK              	"\x1b[40m"      //Black
#define BG_COLOR_RED                	"\x1b[41m"      //Red
#define BG_COLOR_GREEN              	"\x1b[42m"      //Green
#define BG_COLOR_YELLOW             	"\x1b[43m"      //Yellow
#define BG_COLOR_BLUE               	"\x1b[44m"      //Blue
#define BG_COLOR_MAGNETA            	"\x1b[45m"      //Magenta
#define BG_COLOR_CYAN               	"\x1b[46m"      //Cyan
#define BG_COLOR_WHITE              	"\x1b[47m"      //White
#define BG_COLOR_DEFAULT            	"\x1b[49m"      //Default(background color at startup)
#define BG_COLOR_LIGHT_GRAY         	"\x1b[100m"     //Light Gray
#define BG_COLOR_LIGHT_RED          	"\x1b[101m"     //Light Red
#define BG_COLOR_LIGHT_GREEN        	"\x1b[102m"     //Light Green
#define BG_COLOR_LIGHT_YELLOW       	"\x1b[103m"     //Light Yellow
#define BG_COLOR_LIGHT_BLUE         	"\x1b[104m"     //Light Blue
#define BG_COLOR_LIGHT_MAGNETA      	"\x1b[105m"     //Light Magenta
#define BG_COLOR_LIGHT_CYAN         	"\x1b[106m"     //Light Cyan
#define BG_COLOR_LIGHT_WHITE        	"\x1b[107m"     //Light White












// *****************************************************************************
// uptime 잴 때 사용..
// *****************************************************************************
#define DAY_TO_SEC  (24*60*60)
#define HOUR_TO_SEC (60*60)
#define MIN_TO_SEC  (60)

#define CONFIG_FILE_NAME			"SMB_Ariel_Config"
#define CONFIG_CRC_FILE_NAME		"SMB_Ariel_Config_CRC"
#define FW_UPGRADE_HISTORY_FILE		"fw_upgrade_history.txt"
#define SMB_CONFIG_STRING_SIZE_MAX	100

#endif /* INC_HEAD_HEAD_DEF_H_ */
