/**
 ******************************************************************************
  * File Name          : head_data.h
  * Description        : This file is generated by 위대한 송 인재 on Jul 30, 2025
 ******************************************************************************
 *
 * COPYRIGHT(c) 2024 DSN Co. Ltd.
 *
 * Redistribution and use in source and binary forms, with or without modification,
 * are permitted provided that the following conditions are met:
 *   1. Redistributions of source code must retain the above copyright notice,
 *      this list of conditions and the following disclaimer.
 *   2. Redistributions in binary form must reproduce the above copyright notice,
 *      this list of conditions and the following disclaimer in the documentation
 *      and/or other materials provided with the distribution.
 *   3. Neither the name of STMicroelectronics nor the names of its contributors
 *      may be used to endorse or promote products derived from this software
 *      without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 *
 ******************************************************************************
 */


#ifndef INC_HEAD_HEAD_DATA_H_
#define INC_HEAD_HEAD_DATA_H_









extern osMessageQueueId_t		managerThreadQ;
extern uint8_t 				ims_rx_buffer[];
extern manager_msg_func		manager_msg_handler_tbl[];

extern __IO   uint16_t   aADCxConvertedData[]; /* ADC group regular conversion data (array of data) */
extern SMB_adc_value_t SMB_adc_value;
extern SMBIntrObj_t	SMBIntrObj;
extern osTimerEntry_t	osTimerList[];
extern SPIF_HandleTypeDef spif_handle;
extern lfs_t lfs;
extern bool	IsFS_mount;
extern struct lfs_config smb_lfs_config;
extern osThreadId_t Thread_CLI_Handler;
extern UART_HandleTypeDef huart1;
extern SMB_StatusObj_t SMB_StatusObj;
extern SMB_ConfigObj_t SMB_ConfigObj;
extern SMB_ControlObj_t SMB_ControlObj;

#endif /* INC_HEAD_HEAD_DATA_H_ */
